// src/app.ts
import { toNodeHandler } from "better-auth/node";
import cors from "cors";
import "dotenv/config";
import express from "express";

// src/lib/auth.ts
import { betterAuth } from "better-auth";
import { prismaAdapter } from "better-auth/adapters/prisma";

// src/lib/prisma.ts
import { PrismaPg } from "@prisma/adapter-pg";

// generated/prisma/client.ts
import * as path from "path";
import { fileURLToPath } from "url";

// generated/prisma/internal/class.ts
import * as runtime from "@prisma/client/runtime/client";
var config = {
  "previewFeatures": [],
  "clientVersion": "7.8.0",
  "engineVersion": "3c6e192761c0362d496ed980de936e2f3cebcd3a",
  "activeProvider": "postgresql",
  "inlineSchema": 'generator client {\n  provider = "prisma-client"\n  output   = "../generated/prisma"\n}\n\ndatasource db {\n  provider = "postgresql"\n}\n\n//* Enum - BookingStatus\nenum BookingStatus {\n  CONFIRMED\n  COMPLETED\n  CANCELLED\n}\n\n//* Enum - UserRole\nenum UserRole {\n  STUDENT\n  TUTOR\n  ADMIN\n}\n\n//* Model - User\nmodel User {\n  id            String    @id\n  name          String\n  email         String    @unique\n  emailVerified Boolean   @default(false)\n  image         String?\n  role          UserRole  @default(STUDENT)\n  banned        Boolean?  @default(false)\n  banReason     String?\n  banExpires    DateTime?\n\n  sessions Session[]\n  accounts Account[]\n\n  createdAt       DateTime      @default(now())\n  updatedAt       DateTime      @updatedAt\n  tutorProfile    TutorProfile?\n  studentBookings Booking[]     @relation("StudentBookings")\n  tutorBookings   Booking[]     @relation("TutorBookings")\n  studentReviews  Review[]      @relation("StudentReviews")\n  tutorReviews    Review[]      @relation("TutorReviews")\n\n  @@map("user")\n}\n\n//* Model - Account\nmodel Account {\n  id           String  @id\n  userId       String\n  accountId    String\n  providerId   String\n  accessToken  String?\n  refreshToken String?\n  idToken      String?\n  scope        String?\n  password     String?\n\n  user User @relation(fields: [userId], references: [id], onDelete: Cascade)\n\n  accessTokenExpiresAt  DateTime?\n  refreshTokenExpiresAt DateTime?\n  createdAt             DateTime  @default(now())\n  updatedAt             DateTime  @updatedAt\n\n  @@index([userId])\n  @@map("account")\n}\n\n//* Model - Tutor Profile\nmodel TutorProfile {\n  id          String  @id @default(cuid())\n  userId      String  @unique\n  designation String? @db.VarChar(60)\n  bio         String? @db.VarChar(250)\n  hourlyRate  Int     @db.SmallInt\n\n  createdAt DateTime @default(now()) @db.Timestamptz\n  updatedAt DateTime @updatedAt @db.Timestamptz\n\n  user            User            @relation(fields: [userId], references: [id], onDelete: Cascade)\n  tutorCategories TutorCategory[]\n\n  @@index([userId])\n  @@map("tutor_profile")\n}\n\n//* Model - Session\nmodel Session {\n  id             String  @id\n  userId         String\n  token          String\n  ipAddress      String?\n  userAgent      String?\n  impersonatedBy String?\n\n  user User @relation(fields: [userId], references: [id], onDelete: Cascade)\n\n  expiresAt DateTime\n  createdAt DateTime @default(now())\n  updatedAt DateTime @updatedAt\n\n  @@unique([token])\n  @@index([userId])\n  @@map("session")\n}\n\n//* Model - Category\nmodel Category {\n  id          String  @id @default(cuid())\n  name        String  @unique @db.VarChar(30)\n  slug        String  @unique @db.VarChar(30)\n  description String? @db.VarChar(200)\n\n  createdAt DateTime @default(now()) @db.Timestamptz\n  updatedAt DateTime @updatedAt @db.Timestamptz\n\n  tutorCategories TutorCategory[]\n\n  @@map("category")\n}\n\n//* Junction Model - Tutor Category\nmodel TutorCategory {\n  tutorId    String\n  categoryId String\n\n  tutor    TutorProfile @relation(fields: [tutorId], references: [id], onDelete: Cascade)\n  category Category     @relation(fields: [categoryId], references: [id], onDelete: Cascade)\n\n  @@id([tutorId, categoryId])\n  @@map("tutor_category")\n}\n\n//* Model - Review\nmodel Review {\n  id        String  @id @default(cuid())\n  studentId String?\n  tutorId   String\n  rating    Decimal @db.Decimal(2, 1)\n  feedback  String  @db.VarChar(200)\n\n  createdAt DateTime @default(now()) @db.Timestamptz\n\n  student User? @relation("StudentReviews", fields: [studentId], references: [id], onDelete: Cascade)\n  tutor   User? @relation("TutorReviews", fields: [tutorId], references: [id], onDelete: Cascade)\n\n  @@index([studentId])\n  @@index([tutorId])\n  @@map("review")\n}\n\n//* Model - Booking\nmodel Booking {\n  id        String        @id @default(cuid())\n  studentId String?\n  tutorId   String?\n  topic     String        @db.VarChar(100)\n  dueTime   DateTime      @db.Timestamptz\n  duration  Int           @db.SmallInt\n  notes     String?       @db.VarChar(200)\n  status    BookingStatus @default(CONFIRMED)\n\n  createdAt DateTime @default(now()) @db.Timestamptz\n  updatedAt DateTime @updatedAt @db.Timestamptz\n\n  student User? @relation("StudentBookings", fields: [studentId], references: [id], onDelete: Cascade)\n  tutor   User? @relation("TutorBookings", fields: [tutorId], references: [id], onDelete: Cascade)\n\n  @@index([studentId])\n  @@index([tutorId])\n  @@map("booking")\n}\n\n//* Model - Verification\nmodel Verification {\n  id         String @id\n  identifier String\n  value      String\n\n  expiresAt DateTime\n  createdAt DateTime @default(now())\n  updatedAt DateTime @updatedAt\n\n  @@index([identifier])\n  @@map("verification")\n}\n',
  "runtimeDataModel": {
    "models": {},
    "enums": {},
    "types": {}
  },
  "parameterizationSchema": {
    "strings": [],
    "graph": ""
  }
};
config.runtimeDataModel = JSON.parse('{"models":{"User":{"fields":[{"name":"id","kind":"scalar","type":"String"},{"name":"name","kind":"scalar","type":"String"},{"name":"email","kind":"scalar","type":"String"},{"name":"emailVerified","kind":"scalar","type":"Boolean"},{"name":"image","kind":"scalar","type":"String"},{"name":"role","kind":"enum","type":"UserRole"},{"name":"banned","kind":"scalar","type":"Boolean"},{"name":"banReason","kind":"scalar","type":"String"},{"name":"banExpires","kind":"scalar","type":"DateTime"},{"name":"sessions","kind":"object","type":"Session","relationName":"SessionToUser"},{"name":"accounts","kind":"object","type":"Account","relationName":"AccountToUser"},{"name":"createdAt","kind":"scalar","type":"DateTime"},{"name":"updatedAt","kind":"scalar","type":"DateTime"},{"name":"tutorProfile","kind":"object","type":"TutorProfile","relationName":"TutorProfileToUser"},{"name":"studentBookings","kind":"object","type":"Booking","relationName":"StudentBookings"},{"name":"tutorBookings","kind":"object","type":"Booking","relationName":"TutorBookings"},{"name":"studentReviews","kind":"object","type":"Review","relationName":"StudentReviews"},{"name":"tutorReviews","kind":"object","type":"Review","relationName":"TutorReviews"}],"dbName":"user"},"Account":{"fields":[{"name":"id","kind":"scalar","type":"String"},{"name":"userId","kind":"scalar","type":"String"},{"name":"accountId","kind":"scalar","type":"String"},{"name":"providerId","kind":"scalar","type":"String"},{"name":"accessToken","kind":"scalar","type":"String"},{"name":"refreshToken","kind":"scalar","type":"String"},{"name":"idToken","kind":"scalar","type":"String"},{"name":"scope","kind":"scalar","type":"String"},{"name":"password","kind":"scalar","type":"String"},{"name":"user","kind":"object","type":"User","relationName":"AccountToUser"},{"name":"accessTokenExpiresAt","kind":"scalar","type":"DateTime"},{"name":"refreshTokenExpiresAt","kind":"scalar","type":"DateTime"},{"name":"createdAt","kind":"scalar","type":"DateTime"},{"name":"updatedAt","kind":"scalar","type":"DateTime"}],"dbName":"account"},"TutorProfile":{"fields":[{"name":"id","kind":"scalar","type":"String"},{"name":"userId","kind":"scalar","type":"String"},{"name":"designation","kind":"scalar","type":"String"},{"name":"bio","kind":"scalar","type":"String"},{"name":"hourlyRate","kind":"scalar","type":"Int"},{"name":"createdAt","kind":"scalar","type":"DateTime"},{"name":"updatedAt","kind":"scalar","type":"DateTime"},{"name":"user","kind":"object","type":"User","relationName":"TutorProfileToUser"},{"name":"tutorCategories","kind":"object","type":"TutorCategory","relationName":"TutorCategoryToTutorProfile"}],"dbName":"tutor_profile"},"Session":{"fields":[{"name":"id","kind":"scalar","type":"String"},{"name":"userId","kind":"scalar","type":"String"},{"name":"token","kind":"scalar","type":"String"},{"name":"ipAddress","kind":"scalar","type":"String"},{"name":"userAgent","kind":"scalar","type":"String"},{"name":"impersonatedBy","kind":"scalar","type":"String"},{"name":"user","kind":"object","type":"User","relationName":"SessionToUser"},{"name":"expiresAt","kind":"scalar","type":"DateTime"},{"name":"createdAt","kind":"scalar","type":"DateTime"},{"name":"updatedAt","kind":"scalar","type":"DateTime"}],"dbName":"session"},"Category":{"fields":[{"name":"id","kind":"scalar","type":"String"},{"name":"name","kind":"scalar","type":"String"},{"name":"slug","kind":"scalar","type":"String"},{"name":"description","kind":"scalar","type":"String"},{"name":"createdAt","kind":"scalar","type":"DateTime"},{"name":"updatedAt","kind":"scalar","type":"DateTime"},{"name":"tutorCategories","kind":"object","type":"TutorCategory","relationName":"CategoryToTutorCategory"}],"dbName":"category"},"TutorCategory":{"fields":[{"name":"tutorId","kind":"scalar","type":"String"},{"name":"categoryId","kind":"scalar","type":"String"},{"name":"tutor","kind":"object","type":"TutorProfile","relationName":"TutorCategoryToTutorProfile"},{"name":"category","kind":"object","type":"Category","relationName":"CategoryToTutorCategory"}],"dbName":"tutor_category"},"Review":{"fields":[{"name":"id","kind":"scalar","type":"String"},{"name":"studentId","kind":"scalar","type":"String"},{"name":"tutorId","kind":"scalar","type":"String"},{"name":"rating","kind":"scalar","type":"Decimal"},{"name":"feedback","kind":"scalar","type":"String"},{"name":"createdAt","kind":"scalar","type":"DateTime"},{"name":"student","kind":"object","type":"User","relationName":"StudentReviews"},{"name":"tutor","kind":"object","type":"User","relationName":"TutorReviews"}],"dbName":"review"},"Booking":{"fields":[{"name":"id","kind":"scalar","type":"String"},{"name":"studentId","kind":"scalar","type":"String"},{"name":"tutorId","kind":"scalar","type":"String"},{"name":"topic","kind":"scalar","type":"String"},{"name":"dueTime","kind":"scalar","type":"DateTime"},{"name":"duration","kind":"scalar","type":"Int"},{"name":"notes","kind":"scalar","type":"String"},{"name":"status","kind":"enum","type":"BookingStatus"},{"name":"createdAt","kind":"scalar","type":"DateTime"},{"name":"updatedAt","kind":"scalar","type":"DateTime"},{"name":"student","kind":"object","type":"User","relationName":"StudentBookings"},{"name":"tutor","kind":"object","type":"User","relationName":"TutorBookings"}],"dbName":"booking"},"Verification":{"fields":[{"name":"id","kind":"scalar","type":"String"},{"name":"identifier","kind":"scalar","type":"String"},{"name":"value","kind":"scalar","type":"String"},{"name":"expiresAt","kind":"scalar","type":"DateTime"},{"name":"createdAt","kind":"scalar","type":"DateTime"},{"name":"updatedAt","kind":"scalar","type":"DateTime"}],"dbName":"verification"}},"enums":{},"types":{}}');
config.parameterizationSchema = {
  strings: JSON.parse('["where","orderBy","cursor","user","sessions","accounts","tutor","tutorCategories","_count","category","tutorProfile","student","studentBookings","tutorBookings","studentReviews","tutorReviews","User.findUnique","User.findUniqueOrThrow","User.findFirst","User.findFirstOrThrow","User.findMany","data","User.createOne","User.createMany","User.createManyAndReturn","User.updateOne","User.updateMany","User.updateManyAndReturn","create","update","User.upsertOne","User.deleteOne","User.deleteMany","having","_min","_max","User.groupBy","User.aggregate","Account.findUnique","Account.findUniqueOrThrow","Account.findFirst","Account.findFirstOrThrow","Account.findMany","Account.createOne","Account.createMany","Account.createManyAndReturn","Account.updateOne","Account.updateMany","Account.updateManyAndReturn","Account.upsertOne","Account.deleteOne","Account.deleteMany","Account.groupBy","Account.aggregate","TutorProfile.findUnique","TutorProfile.findUniqueOrThrow","TutorProfile.findFirst","TutorProfile.findFirstOrThrow","TutorProfile.findMany","TutorProfile.createOne","TutorProfile.createMany","TutorProfile.createManyAndReturn","TutorProfile.updateOne","TutorProfile.updateMany","TutorProfile.updateManyAndReturn","TutorProfile.upsertOne","TutorProfile.deleteOne","TutorProfile.deleteMany","_avg","_sum","TutorProfile.groupBy","TutorProfile.aggregate","Session.findUnique","Session.findUniqueOrThrow","Session.findFirst","Session.findFirstOrThrow","Session.findMany","Session.createOne","Session.createMany","Session.createManyAndReturn","Session.updateOne","Session.updateMany","Session.updateManyAndReturn","Session.upsertOne","Session.deleteOne","Session.deleteMany","Session.groupBy","Session.aggregate","Category.findUnique","Category.findUniqueOrThrow","Category.findFirst","Category.findFirstOrThrow","Category.findMany","Category.createOne","Category.createMany","Category.createManyAndReturn","Category.updateOne","Category.updateMany","Category.updateManyAndReturn","Category.upsertOne","Category.deleteOne","Category.deleteMany","Category.groupBy","Category.aggregate","TutorCategory.findUnique","TutorCategory.findUniqueOrThrow","TutorCategory.findFirst","TutorCategory.findFirstOrThrow","TutorCategory.findMany","TutorCategory.createOne","TutorCategory.createMany","TutorCategory.createManyAndReturn","TutorCategory.updateOne","TutorCategory.updateMany","TutorCategory.updateManyAndReturn","TutorCategory.upsertOne","TutorCategory.deleteOne","TutorCategory.deleteMany","TutorCategory.groupBy","TutorCategory.aggregate","Review.findUnique","Review.findUniqueOrThrow","Review.findFirst","Review.findFirstOrThrow","Review.findMany","Review.createOne","Review.createMany","Review.createManyAndReturn","Review.updateOne","Review.updateMany","Review.updateManyAndReturn","Review.upsertOne","Review.deleteOne","Review.deleteMany","Review.groupBy","Review.aggregate","Booking.findUnique","Booking.findUniqueOrThrow","Booking.findFirst","Booking.findFirstOrThrow","Booking.findMany","Booking.createOne","Booking.createMany","Booking.createManyAndReturn","Booking.updateOne","Booking.updateMany","Booking.updateManyAndReturn","Booking.upsertOne","Booking.deleteOne","Booking.deleteMany","Booking.groupBy","Booking.aggregate","Verification.findUnique","Verification.findUniqueOrThrow","Verification.findFirst","Verification.findFirstOrThrow","Verification.findMany","Verification.createOne","Verification.createMany","Verification.createManyAndReturn","Verification.updateOne","Verification.updateMany","Verification.updateManyAndReturn","Verification.upsertOne","Verification.deleteOne","Verification.deleteMany","Verification.groupBy","Verification.aggregate","AND","OR","NOT","id","identifier","value","expiresAt","createdAt","updatedAt","equals","in","notIn","lt","lte","gt","gte","not","contains","startsWith","endsWith","studentId","tutorId","topic","dueTime","duration","notes","BookingStatus","status","rating","feedback","categoryId","name","slug","description","every","some","none","userId","token","ipAddress","userAgent","impersonatedBy","designation","bio","hourlyRate","accountId","providerId","accessToken","refreshToken","idToken","scope","password","accessTokenExpiresAt","refreshTokenExpiresAt","email","emailVerified","image","UserRole","role","banned","banReason","banExpires","tutorId_categoryId","is","isNot","connectOrCreate","upsert","createMany","set","disconnect","delete","connect","updateMany","deleteMany","increment","decrement","multiply","divide"]'),
  graph: "rgRSkAEVBAAAuQIAIAUAALoCACAKAAC7AgAgDAAAvAIAIA0AALwCACAOAAC9AgAgDwAAvQIAIKgBAAC0AgAwqQEAABgAEKoBAAC0AgAwqwEBAAAAAa8BQACJAgAhsAFAAIkCACHHAQEAiAIAId4BAQAAAAHfASAAtQIAIeABAQCcAgAh4gEAALYC4gEi4wEgALcCACHkAQEAnAIAIeUBQAC4AgAhAQAAAAEAIA0DAACiAgAgqAEAAMUCADCpAQAAAwAQqgEAAMUCADCrAQEAiAIAIa4BQACJAgAhrwFAAIkCACGwAUAAiQIAIc0BAQCIAgAhzgEBAIgCACHPAQEAnAIAIdABAQCcAgAh0QEBAJwCACEEAwAAkgMAIM8BAADLAgAg0AEAAMsCACDRAQAAywIAIA0DAACiAgAgqAEAAMUCADCpAQAAAwAQqgEAAMUCADCrAQEAAAABrgFAAIkCACGvAUAAiQIAIbABQACJAgAhzQEBAIgCACHOAQEAAAABzwEBAJwCACHQAQEAnAIAIdEBAQCcAgAhAwAAAAMAIAEAAAQAMAIAAAUAIBEDAACiAgAgqAEAAMQCADCpAQAABwAQqgEAAMQCADCrAQEAiAIAIa8BQACJAgAhsAFAAIkCACHNAQEAiAIAIdUBAQCIAgAh1gEBAIgCACHXAQEAnAIAIdgBAQCcAgAh2QEBAJwCACHaAQEAnAIAIdsBAQCcAgAh3AFAALgCACHdAUAAuAIAIQgDAACSAwAg1wEAAMsCACDYAQAAywIAINkBAADLAgAg2gEAAMsCACDbAQAAywIAINwBAADLAgAg3QEAAMsCACARAwAAogIAIKgBAADEAgAwqQEAAAcAEKoBAADEAgAwqwEBAAAAAa8BQACJAgAhsAFAAIkCACHNAQEAiAIAIdUBAQCIAgAh1gEBAIgCACHXAQEAnAIAIdgBAQCcAgAh2QEBAJwCACHaAQEAnAIAIdsBAQCcAgAh3AFAALgCACHdAUAAuAIAIQMAAAAHACABAAAIADACAAAJACAMAwAAogIAIAcAAJ0CACCoAQAAoAIAMKkBAAALABCqAQAAoAIAMKsBAQCIAgAhrwFAAIkCACGwAUAAiQIAIc0BAQCIAgAh0gEBAJwCACHTAQEAnAIAIdQBAgChAgAhAQAAAAsAIAcGAADCAgAgCQAAwwIAIKgBAADBAgAwqQEAAA0AEKoBAADBAgAwvQEBAIgCACHGAQEAiAIAIQIGAAD2AwAgCQAA-QMAIAgGAADCAgAgCQAAwwIAIKgBAADBAgAwqQEAAA0AEKoBAADBAgAwvQEBAIgCACHGAQEAiAIAIeYBAADAAgAgAwAAAA0AIAEAAA4AMAIAAA8AIAMAAAANACABAAAOADACAAAPACABAAAADQAgAQAAAA0AIA8GAACzAgAgCwAAswIAIKgBAAC-AgAwqQEAABQAEKoBAAC-AgAwqwEBAIgCACGvAUAAiQIAIbABQACJAgAhvAEBAJwCACG9AQEAnAIAIb4BAQCIAgAhvwFAAIkCACHAAQIAoQIAIcEBAQCcAgAhwwEAAL8CwwEiBQYAAJIDACALAACSAwAgvAEAAMsCACC9AQAAywIAIMEBAADLAgAgDwYAALMCACALAACzAgAgqAEAAL4CADCpAQAAFAAQqgEAAL4CADCrAQEAAAABrwFAAIkCACGwAUAAiQIAIbwBAQCcAgAhvQEBAJwCACG-AQEAiAIAIb8BQACJAgAhwAECAKECACHBAQEAnAIAIcMBAAC_AsMBIgMAAAAUACABAAAVADACAAAWACAVBAAAuQIAIAUAALoCACAKAAC7AgAgDAAAvAIAIA0AALwCACAOAAC9AgAgDwAAvQIAIKgBAAC0AgAwqQEAABgAEKoBAAC0AgAwqwEBAIgCACGvAUAAiQIAIbABQACJAgAhxwEBAIgCACHeAQEAiAIAId8BIAC1AgAh4AEBAJwCACHiAQAAtgLiASLjASAAtwIAIeQBAQCcAgAh5QFAALgCACEBAAAAGAAgAQAAABgAIAMAAAAUACABAAAVADACAAAWACALBgAAswIAIAsAALMCACCoAQAAsQIAMKkBAAAcABCqAQAAsQIAMKsBAQCIAgAhrwFAAIkCACG8AQEAnAIAIb0BAQCIAgAhxAEQALICACHFAQEAiAIAIQMGAACSAwAgCwAAkgMAILwBAADLAgAgCwYAALMCACALAACzAgAgqAEAALECADCpAQAAHAAQqgEAALECADCrAQEAAAABrwFAAIkCACG8AQEAnAIAIb0BAQCIAgAhxAEQALICACHFAQEAiAIAIQMAAAAcACABAAAdADACAAAeACABAAAAGAAgAQAAABgAIAMAAAAcACABAAAdADACAAAeACABAAAAAwAgAQAAAAcAIAEAAAAUACABAAAAFAAgAQAAABwAIAEAAAAcACABAAAAAQAgCwQAAPQDACAFAAD1AwAgCgAA9gMAIAwAAPcDACANAAD3AwAgDgAA-AMAIA8AAPgDACDgAQAAywIAIOMBAADLAgAg5AEAAMsCACDlAQAAywIAIAMAAAAYACABAAAqADACAAABACADAAAAGAAgAQAAKgAwAgAAAQAgAwAAABgAIAEAACoAMAIAAAEAIBIEAADtAwAgBQAA7gMAIAoAAO8DACAMAADwAwAgDQAA8QMAIA4AAPIDACAPAADzAwAgqwEBAAAAAa8BQAAAAAGwAUAAAAABxwEBAAAAAd4BAQAAAAHfASAAAAAB4AEBAAAAAeIBAAAA4gEC4wEgAAAAAeQBAQAAAAHlAUAAAAABARUAAC4AIAurAQEAAAABrwFAAAAAAbABQAAAAAHHAQEAAAAB3gEBAAAAAd8BIAAAAAHgAQEAAAAB4gEAAADiAQLjASAAAAAB5AEBAAAAAeUBQAAAAAEBFQAAMAAwARUAADAAMBIEAACfAwAgBQAAoAMAIAoAAKEDACAMAACiAwAgDQAAowMAIA4AAKQDACAPAAClAwAgqwEBAMkCACGvAUAAygIAIbABQADKAgAhxwEBAMkCACHeAQEAyQIAId8BIACcAwAh4AEBANICACHiAQAAnQPiASLjASAAngMAIeQBAQDSAgAh5QFAAJYDACECAAAAAQAgFQAAMwAgC6sBAQDJAgAhrwFAAMoCACGwAUAAygIAIccBAQDJAgAh3gEBAMkCACHfASAAnAMAIeABAQDSAgAh4gEAAJ0D4gEi4wEgAJ4DACHkAQEA0gIAIeUBQACWAwAhAgAAABgAIBUAADUAIAIAAAAYACAVAAA1ACADAAAAAQAgHAAALgAgHQAAMwAgAQAAAAEAIAEAAAAYACAHCAAAmQMAICIAAJsDACAjAACaAwAg4AEAAMsCACDjAQAAywIAIOQBAADLAgAg5QEAAMsCACAOqAEAAKcCADCpAQAAPAAQqgEAAKcCADCrAQEAgAIAIa8BQACBAgAhsAFAAIECACHHAQEAgAIAId4BAQCAAgAh3wEgAKgCACHgAQEAiwIAIeIBAACpAuIBIuMBIACqAgAh5AEBAIsCACHlAUAApAIAIQMAAAAYACABAAA7ADAhAAA8ACADAAAAGAAgAQAAKgAwAgAAAQAgAQAAAAkAIAEAAAAJACADAAAABwAgAQAACAAwAgAACQAgAwAAAAcAIAEAAAgAMAIAAAkAIAMAAAAHACABAAAIADACAAAJACAOAwAAmAMAIKsBAQAAAAGvAUAAAAABsAFAAAAAAc0BAQAAAAHVAQEAAAAB1gEBAAAAAdcBAQAAAAHYAQEAAAAB2QEBAAAAAdoBAQAAAAHbAQEAAAAB3AFAAAAAAd0BQAAAAAEBFQAARAAgDasBAQAAAAGvAUAAAAABsAFAAAAAAc0BAQAAAAHVAQEAAAAB1gEBAAAAAdcBAQAAAAHYAQEAAAAB2QEBAAAAAdoBAQAAAAHbAQEAAAAB3AFAAAAAAd0BQAAAAAEBFQAARgAwARUAAEYAMA4DAACXAwAgqwEBAMkCACGvAUAAygIAIbABQADKAgAhzQEBAMkCACHVAQEAyQIAIdYBAQDJAgAh1wEBANICACHYAQEA0gIAIdkBAQDSAgAh2gEBANICACHbAQEA0gIAIdwBQACWAwAh3QFAAJYDACECAAAACQAgFQAASQAgDasBAQDJAgAhrwFAAMoCACGwAUAAygIAIc0BAQDJAgAh1QEBAMkCACHWAQEAyQIAIdcBAQDSAgAh2AEBANICACHZAQEA0gIAIdoBAQDSAgAh2wEBANICACHcAUAAlgMAId0BQACWAwAhAgAAAAcAIBUAAEsAIAIAAAAHACAVAABLACADAAAACQAgHAAARAAgHQAASQAgAQAAAAkAIAEAAAAHACAKCAAAkwMAICIAAJUDACAjAACUAwAg1wEAAMsCACDYAQAAywIAINkBAADLAgAg2gEAAMsCACDbAQAAywIAINwBAADLAgAg3QEAAMsCACAQqAEAAKMCADCpAQAAUgAQqgEAAKMCADCrAQEAgAIAIa8BQACBAgAhsAFAAIECACHNAQEAgAIAIdUBAQCAAgAh1gEBAIACACHXAQEAiwIAIdgBAQCLAgAh2QEBAIsCACHaAQEAiwIAIdsBAQCLAgAh3AFAAKQCACHdAUAApAIAIQMAAAAHACABAABRADAhAABSACADAAAABwAgAQAACAAwAgAACQAgDAMAAKICACAHAACdAgAgqAEAAKACADCpAQAACwAQqgEAAKACADCrAQEAAAABrwFAAIkCACGwAUAAiQIAIc0BAQAAAAHSAQEAnAIAIdMBAQCcAgAh1AECAKECACEBAAAAVQAgAQAAAFUAIAQDAACSAwAgBwAA-gIAINIBAADLAgAg0wEAAMsCACADAAAACwAgAQAAWAAwAgAAVQAgAwAAAAsAIAEAAFgAMAIAAFUAIAMAAAALACABAABYADACAABVACAJAwAAkAMAIAcAAJEDACCrAQEAAAABrwFAAAAAAbABQAAAAAHNAQEAAAAB0gEBAAAAAdMBAQAAAAHUAQIAAAABARUAAFwAIAerAQEAAAABrwFAAAAAAbABQAAAAAHNAQEAAAAB0gEBAAAAAdMBAQAAAAHUAQIAAAABARUAAF4AMAEVAABeADAJAwAAhQMAIAcAAIYDACCrAQEAyQIAIa8BQADKAgAhsAFAAMoCACHNAQEAyQIAIdIBAQDSAgAh0wEBANICACHUAQIA0QIAIQIAAABVACAVAABhACAHqwEBAMkCACGvAUAAygIAIbABQADKAgAhzQEBAMkCACHSAQEA0gIAIdMBAQDSAgAh1AECANECACECAAAACwAgFQAAYwAgAgAAAAsAIBUAAGMAIAMAAABVACAcAABcACAdAABhACABAAAAVQAgAQAAAAsAIAcIAACAAwAgIgAAgwMAICMAAIIDACBEAACBAwAgRQAAhAMAINIBAADLAgAg0wEAAMsCACAKqAEAAJ8CADCpAQAAagAQqgEAAJ8CADCrAQEAgAIAIa8BQACBAgAhsAFAAIECACHNAQEAgAIAIdIBAQCLAgAh0wEBAIsCACHUAQIAjAIAIQMAAAALACABAABpADAhAABqACADAAAACwAgAQAAWAAwAgAAVQAgAQAAAAUAIAEAAAAFACADAAAAAwAgAQAABAAwAgAABQAgAwAAAAMAIAEAAAQAMAIAAAUAIAMAAAADACABAAAEADACAAAFACAKAwAA_wIAIKsBAQAAAAGuAUAAAAABrwFAAAAAAbABQAAAAAHNAQEAAAABzgEBAAAAAc8BAQAAAAHQAQEAAAAB0QEBAAAAAQEVAAByACAJqwEBAAAAAa4BQAAAAAGvAUAAAAABsAFAAAAAAc0BAQAAAAHOAQEAAAABzwEBAAAAAdABAQAAAAHRAQEAAAABARUAAHQAMAEVAAB0ADAKAwAA_gIAIKsBAQDJAgAhrgFAAMoCACGvAUAAygIAIbABQADKAgAhzQEBAMkCACHOAQEAyQIAIc8BAQDSAgAh0AEBANICACHRAQEA0gIAIQIAAAAFACAVAAB3ACAJqwEBAMkCACGuAUAAygIAIa8BQADKAgAhsAFAAMoCACHNAQEAyQIAIc4BAQDJAgAhzwEBANICACHQAQEA0gIAIdEBAQDSAgAhAgAAAAMAIBUAAHkAIAIAAAADACAVAAB5ACADAAAABQAgHAAAcgAgHQAAdwAgAQAAAAUAIAEAAAADACAGCAAA-wIAICIAAP0CACAjAAD8AgAgzwEAAMsCACDQAQAAywIAINEBAADLAgAgDKgBAACeAgAwqQEAAIABABCqAQAAngIAMKsBAQCAAgAhrgFAAIECACGvAUAAgQIAIbABQACBAgAhzQEBAIACACHOAQEAgAIAIc8BAQCLAgAh0AEBAIsCACHRAQEAiwIAIQMAAAADACABAAB_ADAhAACAAQAgAwAAAAMAIAEAAAQAMAIAAAUAIAoHAACdAgAgqAEAAJsCADCpAQAAhgEAEKoBAACbAgAwqwEBAAAAAa8BQACJAgAhsAFAAIkCACHHAQEAAAAByAEBAAAAAckBAQCcAgAhAQAAAIMBACABAAAAgwEAIAoHAACdAgAgqAEAAJsCADCpAQAAhgEAEKoBAACbAgAwqwEBAIgCACGvAUAAiQIAIbABQACJAgAhxwEBAIgCACHIAQEAiAIAIckBAQCcAgAhAgcAAPoCACDJAQAAywIAIAMAAACGAQAgAQAAhwEAMAIAAIMBACADAAAAhgEAIAEAAIcBADACAACDAQAgAwAAAIYBACABAACHAQAwAgAAgwEAIAcHAAD5AgAgqwEBAAAAAa8BQAAAAAGwAUAAAAABxwEBAAAAAcgBAQAAAAHJAQEAAAABARUAAIsBACAGqwEBAAAAAa8BQAAAAAGwAUAAAAABxwEBAAAAAcgBAQAAAAHJAQEAAAABARUAAI0BADABFQAAjQEAMAcHAADsAgAgqwEBAMkCACGvAUAAygIAIbABQADKAgAhxwEBAMkCACHIAQEAyQIAIckBAQDSAgAhAgAAAIMBACAVAACQAQAgBqsBAQDJAgAhrwFAAMoCACGwAUAAygIAIccBAQDJAgAhyAEBAMkCACHJAQEA0gIAIQIAAACGAQAgFQAAkgEAIAIAAACGAQAgFQAAkgEAIAMAAACDAQAgHAAAiwEAIB0AAJABACABAAAAgwEAIAEAAACGAQAgBAgAAOkCACAiAADrAgAgIwAA6gIAIMkBAADLAgAgCagBAACaAgAwqQEAAJkBABCqAQAAmgIAMKsBAQCAAgAhrwFAAIECACGwAUAAgQIAIccBAQCAAgAhyAEBAIACACHJAQEAiwIAIQMAAACGAQAgAQAAmAEAMCEAAJkBACADAAAAhgEAIAEAAIcBADACAACDAQAgAQAAAA8AIAEAAAAPACADAAAADQAgAQAADgAwAgAADwAgAwAAAA0AIAEAAA4AMAIAAA8AIAMAAAANACABAAAOADACAAAPACAEBgAA5wIAIAkAAOgCACC9AQEAAAABxgEBAAAAAQEVAAChAQAgAr0BAQAAAAHGAQEAAAABARUAAKMBADABFQAAowEAMAQGAADlAgAgCQAA5gIAIL0BAQDJAgAhxgEBAMkCACECAAAADwAgFQAApgEAIAK9AQEAyQIAIcYBAQDJAgAhAgAAAA0AIBUAAKgBACACAAAADQAgFQAAqAEAIAMAAAAPACAcAAChAQAgHQAApgEAIAEAAAAPACABAAAADQAgAwgAAOICACAiAADkAgAgIwAA4wIAIAWoAQAAmQIAMKkBAACvAQAQqgEAAJkCADC9AQEAgAIAIcYBAQCAAgAhAwAAAA0AIAEAAK4BADAhAACvAQAgAwAAAA0AIAEAAA4AMAIAAA8AIAEAAAAeACABAAAAHgAgAwAAABwAIAEAAB0AMAIAAB4AIAMAAAAcACABAAAdADACAAAeACADAAAAHAAgAQAAHQAwAgAAHgAgCAYAAOECACALAADgAgAgqwEBAAAAAa8BQAAAAAG8AQEAAAABvQEBAAAAAcQBEAAAAAHFAQEAAAABARUAALcBACAGqwEBAAAAAa8BQAAAAAG8AQEAAAABvQEBAAAAAcQBEAAAAAHFAQEAAAABARUAALkBADABFQAAuQEAMAEAAAAYACABAAAAGAAgCAYAAN8CACALAADeAgAgqwEBAMkCACGvAUAAygIAIbwBAQDSAgAhvQEBAMkCACHEARAA3QIAIcUBAQDJAgAhAgAAAB4AIBUAAL4BACAGqwEBAMkCACGvAUAAygIAIbwBAQDSAgAhvQEBAMkCACHEARAA3QIAIcUBAQDJAgAhAgAAABwAIBUAAMABACACAAAAHAAgFQAAwAEAIAEAAAAYACABAAAAGAAgAwAAAB4AIBwAALcBACAdAAC-AQAgAQAAAB4AIAEAAAAcACAGCAAA2AIAICIAANsCACAjAADaAgAgRAAA2QIAIEUAANwCACC8AQAAywIAIAmoAQAAlQIAMKkBAADJAQAQqgEAAJUCADCrAQEAgAIAIa8BQACBAgAhvAEBAIsCACG9AQEAgAIAIcQBEACWAgAhxQEBAIACACEDAAAAHAAgAQAAyAEAMCEAAMkBACADAAAAHAAgAQAAHQAwAgAAHgAgAQAAABYAIAEAAAAWACADAAAAFAAgAQAAFQAwAgAAFgAgAwAAABQAIAEAABUAMAIAABYAIAMAAAAUACABAAAVADACAAAWACAMBgAA1wIAIAsAANYCACCrAQEAAAABrwFAAAAAAbABQAAAAAG8AQEAAAABvQEBAAAAAb4BAQAAAAG_AUAAAAABwAECAAAAAcEBAQAAAAHDAQAAAMMBAgEVAADRAQAgCqsBAQAAAAGvAUAAAAABsAFAAAAAAbwBAQAAAAG9AQEAAAABvgEBAAAAAb8BQAAAAAHAAQIAAAABwQEBAAAAAcMBAAAAwwECARUAANMBADABFQAA0wEAMAEAAAAYACABAAAAGAAgDAYAANUCACALAADUAgAgqwEBAMkCACGvAUAAygIAIbABQADKAgAhvAEBANICACG9AQEA0gIAIb4BAQDJAgAhvwFAAMoCACHAAQIA0QIAIcEBAQDSAgAhwwEAANMCwwEiAgAAABYAIBUAANgBACAKqwEBAMkCACGvAUAAygIAIbABQADKAgAhvAEBANICACG9AQEA0gIAIb4BAQDJAgAhvwFAAMoCACHAAQIA0QIAIcEBAQDSAgAhwwEAANMCwwEiAgAAABQAIBUAANoBACACAAAAFAAgFQAA2gEAIAEAAAAYACABAAAAGAAgAwAAABYAIBwAANEBACAdAADYAQAgAQAAABYAIAEAAAAUACAICAAAzAIAICIAAM8CACAjAADOAgAgRAAAzQIAIEUAANACACC8AQAAywIAIL0BAADLAgAgwQEAAMsCACANqAEAAIoCADCpAQAA4wEAEKoBAACKAgAwqwEBAIACACGvAUAAgQIAIbABQACBAgAhvAEBAIsCACG9AQEAiwIAIb4BAQCAAgAhvwFAAIECACHAAQIAjAIAIcEBAQCLAgAhwwEAAI0CwwEiAwAAABQAIAEAAOIBADAhAADjAQAgAwAAABQAIAEAABUAMAIAABYAIAmoAQAAhwIAMKkBAADpAQAQqgEAAIcCADCrAQEAAAABrAEBAIgCACGtAQEAiAIAIa4BQACJAgAhrwFAAIkCACGwAUAAiQIAIQEAAADmAQAgAQAAAOYBACAJqAEAAIcCADCpAQAA6QEAEKoBAACHAgAwqwEBAIgCACGsAQEAiAIAIa0BAQCIAgAhrgFAAIkCACGvAUAAiQIAIbABQACJAgAhAAMAAADpAQAgAQAA6gEAMAIAAOYBACADAAAA6QEAIAEAAOoBADACAADmAQAgAwAAAOkBACABAADqAQAwAgAA5gEAIAarAQEAAAABrAEBAAAAAa0BAQAAAAGuAUAAAAABrwFAAAAAAbABQAAAAAEBFQAA7gEAIAarAQEAAAABrAEBAAAAAa0BAQAAAAGuAUAAAAABrwFAAAAAAbABQAAAAAEBFQAA8AEAMAEVAADwAQAwBqsBAQDJAgAhrAEBAMkCACGtAQEAyQIAIa4BQADKAgAhrwFAAMoCACGwAUAAygIAIQIAAADmAQAgFQAA8wEAIAarAQEAyQIAIawBAQDJAgAhrQEBAMkCACGuAUAAygIAIa8BQADKAgAhsAFAAMoCACECAAAA6QEAIBUAAPUBACACAAAA6QEAIBUAAPUBACADAAAA5gEAIBwAAO4BACAdAADzAQAgAQAAAOYBACABAAAA6QEAIAMIAADGAgAgIgAAyAIAICMAAMcCACAJqAEAAP8BADCpAQAA_AEAEKoBAAD_AQAwqwEBAIACACGsAQEAgAIAIa0BAQCAAgAhrgFAAIECACGvAUAAgQIAIbABQACBAgAhAwAAAOkBACABAAD7AQAwIQAA_AEAIAMAAADpAQAgAQAA6gEAMAIAAOYBACAJqAEAAP8BADCpAQAA_AEAEKoBAAD_AQAwqwEBAIACACGsAQEAgAIAIa0BAQCAAgAhrgFAAIECACGvAUAAgQIAIbABQACBAgAhDggAAIMCACAiAACGAgAgIwAAhgIAILEBAQAAAAGyAQEAAAAEswEBAAAABLQBAQAAAAG1AQEAAAABtgEBAAAAAbcBAQAAAAG4AQEAhQIAIbkBAQAAAAG6AQEAAAABuwEBAAAAAQsIAACDAgAgIgAAhAIAICMAAIQCACCxAUAAAAABsgFAAAAABLMBQAAAAAS0AUAAAAABtQFAAAAAAbYBQAAAAAG3AUAAAAABuAFAAIICACELCAAAgwIAICIAAIQCACAjAACEAgAgsQFAAAAAAbIBQAAAAASzAUAAAAAEtAFAAAAAAbUBQAAAAAG2AUAAAAABtwFAAAAAAbgBQACCAgAhCLEBAgAAAAGyAQIAAAAEswECAAAABLQBAgAAAAG1AQIAAAABtgECAAAAAbcBAgAAAAG4AQIAgwIAIQixAUAAAAABsgFAAAAABLMBQAAAAAS0AUAAAAABtQFAAAAAAbYBQAAAAAG3AUAAAAABuAFAAIQCACEOCAAAgwIAICIAAIYCACAjAACGAgAgsQEBAAAAAbIBAQAAAASzAQEAAAAEtAEBAAAAAbUBAQAAAAG2AQEAAAABtwEBAAAAAbgBAQCFAgAhuQEBAAAAAboBAQAAAAG7AQEAAAABC7EBAQAAAAGyAQEAAAAEswEBAAAABLQBAQAAAAG1AQEAAAABtgEBAAAAAbcBAQAAAAG4AQEAhgIAIbkBAQAAAAG6AQEAAAABuwEBAAAAAQmoAQAAhwIAMKkBAADpAQAQqgEAAIcCADCrAQEAiAIAIawBAQCIAgAhrQEBAIgCACGuAUAAiQIAIa8BQACJAgAhsAFAAIkCACELsQEBAAAAAbIBAQAAAASzAQEAAAAEtAEBAAAAAbUBAQAAAAG2AQEAAAABtwEBAAAAAbgBAQCGAgAhuQEBAAAAAboBAQAAAAG7AQEAAAABCLEBQAAAAAGyAUAAAAAEswFAAAAABLQBQAAAAAG1AUAAAAABtgFAAAAAAbcBQAAAAAG4AUAAhAIAIQ2oAQAAigIAMKkBAADjAQAQqgEAAIoCADCrAQEAgAIAIa8BQACBAgAhsAFAAIECACG8AQEAiwIAIb0BAQCLAgAhvgEBAIACACG_AUAAgQIAIcABAgCMAgAhwQEBAIsCACHDAQAAjQLDASIOCAAAkwIAICIAAJQCACAjAACUAgAgsQEBAAAAAbIBAQAAAAWzAQEAAAAFtAEBAAAAAbUBAQAAAAG2AQEAAAABtwEBAAAAAbgBAQCSAgAhuQEBAAAAAboBAQAAAAG7AQEAAAABDQgAAIMCACAiAACDAgAgIwAAgwIAIEQAAJECACBFAACDAgAgsQECAAAAAbIBAgAAAASzAQIAAAAEtAECAAAAAbUBAgAAAAG2AQIAAAABtwECAAAAAbgBAgCQAgAhBwgAAIMCACAiAACPAgAgIwAAjwIAILEBAAAAwwECsgEAAADDAQizAQAAAMMBCLgBAACOAsMBIgcIAACDAgAgIgAAjwIAICMAAI8CACCxAQAAAMMBArIBAAAAwwEIswEAAADDAQi4AQAAjgLDASIEsQEAAADDAQKyAQAAAMMBCLMBAAAAwwEIuAEAAI8CwwEiDQgAAIMCACAiAACDAgAgIwAAgwIAIEQAAJECACBFAACDAgAgsQECAAAAAbIBAgAAAASzAQIAAAAEtAECAAAAAbUBAgAAAAG2AQIAAAABtwECAAAAAbgBAgCQAgAhCLEBCAAAAAGyAQgAAAAEswEIAAAABLQBCAAAAAG1AQgAAAABtgEIAAAAAbcBCAAAAAG4AQgAkQIAIQ4IAACTAgAgIgAAlAIAICMAAJQCACCxAQEAAAABsgEBAAAABbMBAQAAAAW0AQEAAAABtQEBAAAAAbYBAQAAAAG3AQEAAAABuAEBAJICACG5AQEAAAABugEBAAAAAbsBAQAAAAEIsQECAAAAAbIBAgAAAAWzAQIAAAAFtAECAAAAAbUBAgAAAAG2AQIAAAABtwECAAAAAbgBAgCTAgAhC7EBAQAAAAGyAQEAAAAFswEBAAAABbQBAQAAAAG1AQEAAAABtgEBAAAAAbcBAQAAAAG4AQEAlAIAIbkBAQAAAAG6AQEAAAABuwEBAAAAAQmoAQAAlQIAMKkBAADJAQAQqgEAAJUCADCrAQEAgAIAIa8BQACBAgAhvAEBAIsCACG9AQEAgAIAIcQBEACWAgAhxQEBAIACACENCAAAgwIAICIAAJgCACAjAACYAgAgRAAAmAIAIEUAAJgCACCxARAAAAABsgEQAAAABLMBEAAAAAS0ARAAAAABtQEQAAAAAbYBEAAAAAG3ARAAAAABuAEQAJcCACENCAAAgwIAICIAAJgCACAjAACYAgAgRAAAmAIAIEUAAJgCACCxARAAAAABsgEQAAAABLMBEAAAAAS0ARAAAAABtQEQAAAAAbYBEAAAAAG3ARAAAAABuAEQAJcCACEIsQEQAAAAAbIBEAAAAASzARAAAAAEtAEQAAAAAbUBEAAAAAG2ARAAAAABtwEQAAAAAbgBEACYAgAhBagBAACZAgAwqQEAAK8BABCqAQAAmQIAML0BAQCAAgAhxgEBAIACACEJqAEAAJoCADCpAQAAmQEAEKoBAACaAgAwqwEBAIACACGvAUAAgQIAIbABQACBAgAhxwEBAIACACHIAQEAgAIAIckBAQCLAgAhCgcAAJ0CACCoAQAAmwIAMKkBAACGAQAQqgEAAJsCADCrAQEAiAIAIa8BQACJAgAhsAFAAIkCACHHAQEAiAIAIcgBAQCIAgAhyQEBAJwCACELsQEBAAAAAbIBAQAAAAWzAQEAAAAFtAEBAAAAAbUBAQAAAAG2AQEAAAABtwEBAAAAAbgBAQCUAgAhuQEBAAAAAboBAQAAAAG7AQEAAAABA8oBAAANACDLAQAADQAgzAEAAA0AIAyoAQAAngIAMKkBAACAAQAQqgEAAJ4CADCrAQEAgAIAIa4BQACBAgAhrwFAAIECACGwAUAAgQIAIc0BAQCAAgAhzgEBAIACACHPAQEAiwIAIdABAQCLAgAh0QEBAIsCACEKqAEAAJ8CADCpAQAAagAQqgEAAJ8CADCrAQEAgAIAIa8BQACBAgAhsAFAAIECACHNAQEAgAIAIdIBAQCLAgAh0wEBAIsCACHUAQIAjAIAIQwDAACiAgAgBwAAnQIAIKgBAACgAgAwqQEAAAsAEKoBAACgAgAwqwEBAIgCACGvAUAAiQIAIbABQACJAgAhzQEBAIgCACHSAQEAnAIAIdMBAQCcAgAh1AECAKECACEIsQECAAAAAbIBAgAAAASzAQIAAAAEtAECAAAAAbUBAgAAAAG2AQIAAAABtwECAAAAAbgBAgCDAgAhFwQAALkCACAFAAC6AgAgCgAAuwIAIAwAALwCACANAAC8AgAgDgAAvQIAIA8AAL0CACCoAQAAtAIAMKkBAAAYABCqAQAAtAIAMKsBAQCIAgAhrwFAAIkCACGwAUAAiQIAIccBAQCIAgAh3gEBAIgCACHfASAAtQIAIeABAQCcAgAh4gEAALYC4gEi4wEgALcCACHkAQEAnAIAIeUBQAC4AgAh5wEAABgAIOgBAAAYACAQqAEAAKMCADCpAQAAUgAQqgEAAKMCADCrAQEAgAIAIa8BQACBAgAhsAFAAIECACHNAQEAgAIAIdUBAQCAAgAh1gEBAIACACHXAQEAiwIAIdgBAQCLAgAh2QEBAIsCACHaAQEAiwIAIdsBAQCLAgAh3AFAAKQCACHdAUAApAIAIQsIAACTAgAgIgAApgIAICMAAKYCACCxAUAAAAABsgFAAAAABbMBQAAAAAW0AUAAAAABtQFAAAAAAbYBQAAAAAG3AUAAAAABuAFAAKUCACELCAAAkwIAICIAAKYCACAjAACmAgAgsQFAAAAAAbIBQAAAAAWzAUAAAAAFtAFAAAAAAbUBQAAAAAG2AUAAAAABtwFAAAAAAbgBQAClAgAhCLEBQAAAAAGyAUAAAAAFswFAAAAABbQBQAAAAAG1AUAAAAABtgFAAAAAAbcBQAAAAAG4AUAApgIAIQ6oAQAApwIAMKkBAAA8ABCqAQAApwIAMKsBAQCAAgAhrwFAAIECACGwAUAAgQIAIccBAQCAAgAh3gEBAIACACHfASAAqAIAIeABAQCLAgAh4gEAAKkC4gEi4wEgAKoCACHkAQEAiwIAIeUBQACkAgAhBQgAAIMCACAiAACwAgAgIwAAsAIAILEBIAAAAAG4ASAArwIAIQcIAACDAgAgIgAArgIAICMAAK4CACCxAQAAAOIBArIBAAAA4gEIswEAAADiAQi4AQAArQLiASIFCAAAkwIAICIAAKwCACAjAACsAgAgsQEgAAAAAbgBIACrAgAhBQgAAJMCACAiAACsAgAgIwAArAIAILEBIAAAAAG4ASAAqwIAIQKxASAAAAABuAEgAKwCACEHCAAAgwIAICIAAK4CACAjAACuAgAgsQEAAADiAQKyAQAAAOIBCLMBAAAA4gEIuAEAAK0C4gEiBLEBAAAA4gECsgEAAADiAQizAQAAAOIBCLgBAACuAuIBIgUIAACDAgAgIgAAsAIAICMAALACACCxASAAAAABuAEgAK8CACECsQEgAAAAAbgBIACwAgAhCwYAALMCACALAACzAgAgqAEAALECADCpAQAAHAAQqgEAALECADCrAQEAiAIAIa8BQACJAgAhvAEBAJwCACG9AQEAiAIAIcQBEACyAgAhxQEBAIgCACEIsQEQAAAAAbIBEAAAAASzARAAAAAEtAEQAAAAAbUBEAAAAAG2ARAAAAABtwEQAAAAAbgBEACYAgAhFwQAALkCACAFAAC6AgAgCgAAuwIAIAwAALwCACANAAC8AgAgDgAAvQIAIA8AAL0CACCoAQAAtAIAMKkBAAAYABCqAQAAtAIAMKsBAQCIAgAhrwFAAIkCACGwAUAAiQIAIccBAQCIAgAh3gEBAIgCACHfASAAtQIAIeABAQCcAgAh4gEAALYC4gEi4wEgALcCACHkAQEAnAIAIeUBQAC4AgAh5wEAABgAIOgBAAAYACAVBAAAuQIAIAUAALoCACAKAAC7AgAgDAAAvAIAIA0AALwCACAOAAC9AgAgDwAAvQIAIKgBAAC0AgAwqQEAABgAEKoBAAC0AgAwqwEBAIgCACGvAUAAiQIAIbABQACJAgAhxwEBAIgCACHeAQEAiAIAId8BIAC1AgAh4AEBAJwCACHiAQAAtgLiASLjASAAtwIAIeQBAQCcAgAh5QFAALgCACECsQEgAAAAAbgBIACwAgAhBLEBAAAA4gECsgEAAADiAQizAQAAAOIBCLgBAACuAuIBIgKxASAAAAABuAEgAKwCACEIsQFAAAAAAbIBQAAAAAWzAUAAAAAFtAFAAAAAAbUBQAAAAAG2AUAAAAABtwFAAAAAAbgBQACmAgAhA8oBAAADACDLAQAAAwAgzAEAAAMAIAPKAQAABwAgywEAAAcAIMwBAAAHACAOAwAAogIAIAcAAJ0CACCoAQAAoAIAMKkBAAALABCqAQAAoAIAMKsBAQCIAgAhrwFAAIkCACGwAUAAiQIAIc0BAQCIAgAh0gEBAJwCACHTAQEAnAIAIdQBAgChAgAh5wEAAAsAIOgBAAALACADygEAABQAIMsBAAAUACDMAQAAFAAgA8oBAAAcACDLAQAAHAAgzAEAABwAIA8GAACzAgAgCwAAswIAIKgBAAC-AgAwqQEAABQAEKoBAAC-AgAwqwEBAIgCACGvAUAAiQIAIbABQACJAgAhvAEBAJwCACG9AQEAnAIAIb4BAQCIAgAhvwFAAIkCACHAAQIAoQIAIcEBAQCcAgAhwwEAAL8CwwEiBLEBAAAAwwECsgEAAADDAQizAQAAAMMBCLgBAACPAsMBIgK9AQEAAAABxgEBAAAAAQcGAADCAgAgCQAAwwIAIKgBAADBAgAwqQEAAA0AEKoBAADBAgAwvQEBAIgCACHGAQEAiAIAIQ4DAACiAgAgBwAAnQIAIKgBAACgAgAwqQEAAAsAEKoBAACgAgAwqwEBAIgCACGvAUAAiQIAIbABQACJAgAhzQEBAIgCACHSAQEAnAIAIdMBAQCcAgAh1AECAKECACHnAQAACwAg6AEAAAsAIAwHAACdAgAgqAEAAJsCADCpAQAAhgEAEKoBAACbAgAwqwEBAIgCACGvAUAAiQIAIbABQACJAgAhxwEBAIgCACHIAQEAiAIAIckBAQCcAgAh5wEAAIYBACDoAQAAhgEAIBEDAACiAgAgqAEAAMQCADCpAQAABwAQqgEAAMQCADCrAQEAiAIAIa8BQACJAgAhsAFAAIkCACHNAQEAiAIAIdUBAQCIAgAh1gEBAIgCACHXAQEAnAIAIdgBAQCcAgAh2QEBAJwCACHaAQEAnAIAIdsBAQCcAgAh3AFAALgCACHdAUAAuAIAIQ0DAACiAgAgqAEAAMUCADCpAQAAAwAQqgEAAMUCADCrAQEAiAIAIa4BQACJAgAhrwFAAIkCACGwAUAAiQIAIc0BAQCIAgAhzgEBAIgCACHPAQEAnAIAIdABAQCcAgAh0QEBAJwCACEAAAAB7AEBAAAAAQHsAUAAAAABAAAAAAAABewBAgAAAAHyAQIAAAAB8wECAAAAAfQBAgAAAAH1AQIAAAABAewBAQAAAAEB7AEAAADDAQIHHAAApwQAIB0AAK0EACDpAQAAqAQAIOoBAACsBAAg7QEAABgAIO4BAAAYACDvAQAAAQAgBxwAAKUEACAdAACqBAAg6QEAAKYEACDqAQAAqQQAIO0BAAAYACDuAQAAGAAg7wEAAAEAIAMcAACnBAAg6QEAAKgEACDvAQAAAQAgAxwAAKUEACDpAQAApgQAIO8BAAABACAAAAAAAAXsARAAAAAB8gEQAAAAAfMBEAAAAAH0ARAAAAAB9QEQAAAAAQccAACdBAAgHQAAowQAIOkBAACeBAAg6gEAAKIEACDtAQAAGAAg7gEAABgAIO8BAAABACAHHAAAmwQAIB0AAKAEACDpAQAAnAQAIOoBAACfBAAg7QEAABgAIO4BAAAYACDvAQAAAQAgAxwAAJ0EACDpAQAAngQAIO8BAAABACADHAAAmwQAIOkBAACcBAAg7wEAAAEAIAAAAAUcAACTBAAgHQAAmQQAIOkBAACUBAAg6gEAAJgEACDvAQAAVQAgBRwAAJEEACAdAACWBAAg6QEAAJIEACDqAQAAlQQAIO8BAACDAQAgAxwAAJMEACDpAQAAlAQAIO8BAABVACADHAAAkQQAIOkBAACSBAAg7wEAAIMBACAAAAALHAAA7QIAMB0AAPICADDpAQAA7gIAMOoBAADvAgAw6wEAAPACACDsAQAA8QIAMO0BAADxAgAw7gEAAPECADDvAQAA8QIAMPABAADzAgAw8QEAAPQCADACBgAA5wIAIL0BAQAAAAECAAAADwAgHAAA-AIAIAMAAAAPACAcAAD4AgAgHQAA9wIAIAEVAACQBAAwCAYAAMICACAJAADDAgAgqAEAAMECADCpAQAADQAQqgEAAMECADC9AQEAiAIAIcYBAQCIAgAh5gEAAMACACACAAAADwAgFQAA9wIAIAIAAAD1AgAgFQAA9gIAIAWoAQAA9AIAMKkBAAD1AgAQqgEAAPQCADC9AQEAiAIAIcYBAQCIAgAhBagBAAD0AgAwqQEAAPUCABCqAQAA9AIAML0BAQCIAgAhxgEBAIgCACEBvQEBAMkCACECBgAA5QIAIL0BAQDJAgAhAgYAAOcCACC9AQEAAAABBBwAAO0CADDpAQAA7gIAMOsBAADwAgAg7wEAAPECADAAAAAABRwAAIsEACAdAACOBAAg6QEAAIwEACDqAQAAjQQAIO8BAAABACADHAAAiwQAIOkBAACMBAAg7wEAAAEAIAAAAAAABRwAAIUEACAdAACJBAAg6QEAAIYEACDqAQAAiAQAIO8BAAABACALHAAAhwMAMB0AAIsDADDpAQAAiAMAMOoBAACJAwAw6wEAAIoDACDsAQAA8QIAMO0BAADxAgAw7gEAAPECADDvAQAA8QIAMPABAACMAwAw8QEAAPQCADACCQAA6AIAIMYBAQAAAAECAAAADwAgHAAAjwMAIAMAAAAPACAcAACPAwAgHQAAjgMAIAEVAACHBAAwAgAAAA8AIBUAAI4DACACAAAA9QIAIBUAAI0DACABxgEBAMkCACECCQAA5gIAIMYBAQDJAgAhAgkAAOgCACDGAQEAAAABAxwAAIUEACDpAQAAhgQAIO8BAAABACAEHAAAhwMAMOkBAACIAwAw6wEAAIoDACDvAQAA8QIAMAsEAAD0AwAgBQAA9QMAIAoAAPYDACAMAAD3AwAgDQAA9wMAIA4AAPgDACAPAAD4AwAg4AEAAMsCACDjAQAAywIAIOQBAADLAgAg5QEAAMsCACAAAAAB7AFAAAAAAQUcAACABAAgHQAAgwQAIOkBAACBBAAg6gEAAIIEACDvAQAAAQAgAxwAAIAEACDpAQAAgQQAIO8BAAABACAAAAAB7AEgAAAAAQHsAQAAAOIBAgHsASAAAAABCxwAAOEDADAdAADmAwAw6QEAAOIDADDqAQAA4wMAMOsBAADkAwAg7AEAAOUDADDtAQAA5QMAMO4BAADlAwAw7wEAAOUDADDwAQAA5wMAMPEBAADoAwAwCxwAANUDADAdAADaAwAw6QEAANYDADDqAQAA1wMAMOsBAADYAwAg7AEAANkDADDtAQAA2QMAMO4BAADZAwAw7wEAANkDADDwAQAA2wMAMPEBAADcAwAwBxwAANADACAdAADTAwAg6QEAANEDACDqAQAA0gMAIO0BAAALACDuAQAACwAg7wEAAFUAIAscAADHAwAwHQAAywMAMOkBAADIAwAw6gEAAMkDADDrAQAAygMAIOwBAAC_AwAw7QEAAL8DADDuAQAAvwMAMO8BAAC_AwAw8AEAAMwDADDxAQAAwgMAMAscAAC7AwAwHQAAwAMAMOkBAAC8AwAw6gEAAL0DADDrAQAAvgMAIOwBAAC_AwAw7QEAAL8DADDuAQAAvwMAMO8BAAC_AwAw8AEAAMEDADDxAQAAwgMAMAscAACyAwAwHQAAtgMAMOkBAACzAwAw6gEAALQDADDrAQAAtQMAIOwBAACqAwAw7QEAAKoDADDuAQAAqgMAMO8BAACqAwAw8AEAALcDADDxAQAArQMAMAscAACmAwAwHQAAqwMAMOkBAACnAwAw6gEAAKgDADDrAQAAqQMAIOwBAACqAwAw7QEAAKoDADDuAQAAqgMAMO8BAACqAwAw8AEAAKwDADDxAQAArQMAMAYLAADgAgAgqwEBAAAAAa8BQAAAAAG8AQEAAAABxAEQAAAAAcUBAQAAAAECAAAAHgAgHAAAsQMAIAMAAAAeACAcAACxAwAgHQAAsAMAIAEVAAD_AwAwCwYAALMCACALAACzAgAgqAEAALECADCpAQAAHAAQqgEAALECADCrAQEAAAABrwFAAIkCACG8AQEAnAIAIb0BAQCIAgAhxAEQALICACHFAQEAiAIAIQIAAAAeACAVAACwAwAgAgAAAK4DACAVAACvAwAgCagBAACtAwAwqQEAAK4DABCqAQAArQMAMKsBAQCIAgAhrwFAAIkCACG8AQEAnAIAIb0BAQCIAgAhxAEQALICACHFAQEAiAIAIQmoAQAArQMAMKkBAACuAwAQqgEAAK0DADCrAQEAiAIAIa8BQACJAgAhvAEBAJwCACG9AQEAiAIAIcQBEACyAgAhxQEBAIgCACEFqwEBAMkCACGvAUAAygIAIbwBAQDSAgAhxAEQAN0CACHFAQEAyQIAIQYLAADeAgAgqwEBAMkCACGvAUAAygIAIbwBAQDSAgAhxAEQAN0CACHFAQEAyQIAIQYLAADgAgAgqwEBAAAAAa8BQAAAAAG8AQEAAAABxAEQAAAAAcUBAQAAAAEGBgAA4QIAIKsBAQAAAAGvAUAAAAABvQEBAAAAAcQBEAAAAAHFAQEAAAABAgAAAB4AIBwAALoDACADAAAAHgAgHAAAugMAIB0AALkDACABFQAA_gMAMAIAAAAeACAVAAC5AwAgAgAAAK4DACAVAAC4AwAgBasBAQDJAgAhrwFAAMoCACG9AQEAyQIAIcQBEADdAgAhxQEBAMkCACEGBgAA3wIAIKsBAQDJAgAhrwFAAMoCACG9AQEAyQIAIcQBEADdAgAhxQEBAMkCACEGBgAA4QIAIKsBAQAAAAGvAUAAAAABvQEBAAAAAcQBEAAAAAHFAQEAAAABCgsAANYCACCrAQEAAAABrwFAAAAAAbABQAAAAAG8AQEAAAABvgEBAAAAAb8BQAAAAAHAAQIAAAABwQEBAAAAAcMBAAAAwwECAgAAABYAIBwAAMYDACADAAAAFgAgHAAAxgMAIB0AAMUDACABFQAA_QMAMA8GAACzAgAgCwAAswIAIKgBAAC-AgAwqQEAABQAEKoBAAC-AgAwqwEBAAAAAa8BQACJAgAhsAFAAIkCACG8AQEAnAIAIb0BAQCcAgAhvgEBAIgCACG_AUAAiQIAIcABAgChAgAhwQEBAJwCACHDAQAAvwLDASICAAAAFgAgFQAAxQMAIAIAAADDAwAgFQAAxAMAIA2oAQAAwgMAMKkBAADDAwAQqgEAAMIDADCrAQEAiAIAIa8BQACJAgAhsAFAAIkCACG8AQEAnAIAIb0BAQCcAgAhvgEBAIgCACG_AUAAiQIAIcABAgChAgAhwQEBAJwCACHDAQAAvwLDASINqAEAAMIDADCpAQAAwwMAEKoBAADCAwAwqwEBAIgCACGvAUAAiQIAIbABQACJAgAhvAEBAJwCACG9AQEAnAIAIb4BAQCIAgAhvwFAAIkCACHAAQIAoQIAIcEBAQCcAgAhwwEAAL8CwwEiCasBAQDJAgAhrwFAAMoCACGwAUAAygIAIbwBAQDSAgAhvgEBAMkCACG_AUAAygIAIcABAgDRAgAhwQEBANICACHDAQAA0wLDASIKCwAA1AIAIKsBAQDJAgAhrwFAAMoCACGwAUAAygIAIbwBAQDSAgAhvgEBAMkCACG_AUAAygIAIcABAgDRAgAhwQEBANICACHDAQAA0wLDASIKCwAA1gIAIKsBAQAAAAGvAUAAAAABsAFAAAAAAbwBAQAAAAG-AQEAAAABvwFAAAAAAcABAgAAAAHBAQEAAAABwwEAAADDAQIKBgAA1wIAIKsBAQAAAAGvAUAAAAABsAFAAAAAAb0BAQAAAAG-AQEAAAABvwFAAAAAAcABAgAAAAHBAQEAAAABwwEAAADDAQICAAAAFgAgHAAAzwMAIAMAAAAWACAcAADPAwAgHQAAzgMAIAEVAAD8AwAwAgAAABYAIBUAAM4DACACAAAAwwMAIBUAAM0DACAJqwEBAMkCACGvAUAAygIAIbABQADKAgAhvQEBANICACG-AQEAyQIAIb8BQADKAgAhwAECANECACHBAQEA0gIAIcMBAADTAsMBIgoGAADVAgAgqwEBAMkCACGvAUAAygIAIbABQADKAgAhvQEBANICACG-AQEAyQIAIb8BQADKAgAhwAECANECACHBAQEA0gIAIcMBAADTAsMBIgoGAADXAgAgqwEBAAAAAa8BQAAAAAGwAUAAAAABvQEBAAAAAb4BAQAAAAG_AUAAAAABwAECAAAAAcEBAQAAAAHDAQAAAMMBAgcHAACRAwAgqwEBAAAAAa8BQAAAAAGwAUAAAAAB0gEBAAAAAdMBAQAAAAHUAQIAAAABAgAAAFUAIBwAANADACADAAAACwAgHAAA0AMAIB0AANQDACAJAAAACwAgBwAAhgMAIBUAANQDACCrAQEAyQIAIa8BQADKAgAhsAFAAMoCACHSAQEA0gIAIdMBAQDSAgAh1AECANECACEHBwAAhgMAIKsBAQDJAgAhrwFAAMoCACGwAUAAygIAIdIBAQDSAgAh0wEBANICACHUAQIA0QIAIQyrAQEAAAABrwFAAAAAAbABQAAAAAHVAQEAAAAB1gEBAAAAAdcBAQAAAAHYAQEAAAAB2QEBAAAAAdoBAQAAAAHbAQEAAAAB3AFAAAAAAd0BQAAAAAECAAAACQAgHAAA4AMAIAMAAAAJACAcAADgAwAgHQAA3wMAIAEVAAD7AwAwEQMAAKICACCoAQAAxAIAMKkBAAAHABCqAQAAxAIAMKsBAQAAAAGvAUAAiQIAIbABQACJAgAhzQEBAIgCACHVAQEAiAIAIdYBAQCIAgAh1wEBAJwCACHYAQEAnAIAIdkBAQCcAgAh2gEBAJwCACHbAQEAnAIAIdwBQAC4AgAh3QFAALgCACECAAAACQAgFQAA3wMAIAIAAADdAwAgFQAA3gMAIBCoAQAA3AMAMKkBAADdAwAQqgEAANwDADCrAQEAiAIAIa8BQACJAgAhsAFAAIkCACHNAQEAiAIAIdUBAQCIAgAh1gEBAIgCACHXAQEAnAIAIdgBAQCcAgAh2QEBAJwCACHaAQEAnAIAIdsBAQCcAgAh3AFAALgCACHdAUAAuAIAIRCoAQAA3AMAMKkBAADdAwAQqgEAANwDADCrAQEAiAIAIa8BQACJAgAhsAFAAIkCACHNAQEAiAIAIdUBAQCIAgAh1gEBAIgCACHXAQEAnAIAIdgBAQCcAgAh2QEBAJwCACHaAQEAnAIAIdsBAQCcAgAh3AFAALgCACHdAUAAuAIAIQyrAQEAyQIAIa8BQADKAgAhsAFAAMoCACHVAQEAyQIAIdYBAQDJAgAh1wEBANICACHYAQEA0gIAIdkBAQDSAgAh2gEBANICACHbAQEA0gIAIdwBQACWAwAh3QFAAJYDACEMqwEBAMkCACGvAUAAygIAIbABQADKAgAh1QEBAMkCACHWAQEAyQIAIdcBAQDSAgAh2AEBANICACHZAQEA0gIAIdoBAQDSAgAh2wEBANICACHcAUAAlgMAId0BQACWAwAhDKsBAQAAAAGvAUAAAAABsAFAAAAAAdUBAQAAAAHWAQEAAAAB1wEBAAAAAdgBAQAAAAHZAQEAAAAB2gEBAAAAAdsBAQAAAAHcAUAAAAAB3QFAAAAAAQirAQEAAAABrgFAAAAAAa8BQAAAAAGwAUAAAAABzgEBAAAAAc8BAQAAAAHQAQEAAAAB0QEBAAAAAQIAAAAFACAcAADsAwAgAwAAAAUAIBwAAOwDACAdAADrAwAgARUAAPoDADANAwAAogIAIKgBAADFAgAwqQEAAAMAEKoBAADFAgAwqwEBAAAAAa4BQACJAgAhrwFAAIkCACGwAUAAiQIAIc0BAQCIAgAhzgEBAAAAAc8BAQCcAgAh0AEBAJwCACHRAQEAnAIAIQIAAAAFACAVAADrAwAgAgAAAOkDACAVAADqAwAgDKgBAADoAwAwqQEAAOkDABCqAQAA6AMAMKsBAQCIAgAhrgFAAIkCACGvAUAAiQIAIbABQACJAgAhzQEBAIgCACHOAQEAiAIAIc8BAQCcAgAh0AEBAJwCACHRAQEAnAIAIQyoAQAA6AMAMKkBAADpAwAQqgEAAOgDADCrAQEAiAIAIa4BQACJAgAhrwFAAIkCACGwAUAAiQIAIc0BAQCIAgAhzgEBAIgCACHPAQEAnAIAIdABAQCcAgAh0QEBAJwCACEIqwEBAMkCACGuAUAAygIAIa8BQADKAgAhsAFAAMoCACHOAQEAyQIAIc8BAQDSAgAh0AEBANICACHRAQEA0gIAIQirAQEAyQIAIa4BQADKAgAhrwFAAMoCACGwAUAAygIAIc4BAQDJAgAhzwEBANICACHQAQEA0gIAIdEBAQDSAgAhCKsBAQAAAAGuAUAAAAABrwFAAAAAAbABQAAAAAHOAQEAAAABzwEBAAAAAdABAQAAAAHRAQEAAAABBBwAAOEDADDpAQAA4gMAMOsBAADkAwAg7wEAAOUDADAEHAAA1QMAMOkBAADWAwAw6wEAANgDACDvAQAA2QMAMAMcAADQAwAg6QEAANEDACDvAQAAVQAgBBwAAMcDADDpAQAAyAMAMOsBAADKAwAg7wEAAL8DADAEHAAAuwMAMOkBAAC8AwAw6wEAAL4DACDvAQAAvwMAMAQcAACyAwAw6QEAALMDADDrAQAAtQMAIO8BAACqAwAwBBwAAKYDADDpAQAApwMAMOsBAACpAwAg7wEAAKoDADAAAAQDAACSAwAgBwAA-gIAINIBAADLAgAg0wEAAMsCACAAAAIHAAD6AgAgyQEAAMsCACAIqwEBAAAAAa4BQAAAAAGvAUAAAAABsAFAAAAAAc4BAQAAAAHPAQEAAAAB0AEBAAAAAdEBAQAAAAEMqwEBAAAAAa8BQAAAAAGwAUAAAAAB1QEBAAAAAdYBAQAAAAHXAQEAAAAB2AEBAAAAAdkBAQAAAAHaAQEAAAAB2wEBAAAAAdwBQAAAAAHdAUAAAAABCasBAQAAAAGvAUAAAAABsAFAAAAAAb0BAQAAAAG-AQEAAAABvwFAAAAAAcABAgAAAAHBAQEAAAABwwEAAADDAQIJqwEBAAAAAa8BQAAAAAGwAUAAAAABvAEBAAAAAb4BAQAAAAG_AUAAAAABwAECAAAAAcEBAQAAAAHDAQAAAMMBAgWrAQEAAAABrwFAAAAAAb0BAQAAAAHEARAAAAABxQEBAAAAAQWrAQEAAAABrwFAAAAAAbwBAQAAAAHEARAAAAABxQEBAAAAAREEAADtAwAgCgAA7wMAIAwAAPADACANAADxAwAgDgAA8gMAIA8AAPMDACCrAQEAAAABrwFAAAAAAbABQAAAAAHHAQEAAAAB3gEBAAAAAd8BIAAAAAHgAQEAAAAB4gEAAADiAQLjASAAAAAB5AEBAAAAAeUBQAAAAAECAAAAAQAgHAAAgAQAIAMAAAAYACAcAACABAAgHQAAhAQAIBMAAAAYACAEAACfAwAgCgAAoQMAIAwAAKIDACANAACjAwAgDgAApAMAIA8AAKUDACAVAACEBAAgqwEBAMkCACGvAUAAygIAIbABQADKAgAhxwEBAMkCACHeAQEAyQIAId8BIACcAwAh4AEBANICACHiAQAAnQPiASLjASAAngMAIeQBAQDSAgAh5QFAAJYDACERBAAAnwMAIAoAAKEDACAMAACiAwAgDQAAowMAIA4AAKQDACAPAAClAwAgqwEBAMkCACGvAUAAygIAIbABQADKAgAhxwEBAMkCACHeAQEAyQIAId8BIACcAwAh4AEBANICACHiAQAAnQPiASLjASAAngMAIeQBAQDSAgAh5QFAAJYDACERBAAA7QMAIAUAAO4DACAMAADwAwAgDQAA8QMAIA4AAPIDACAPAADzAwAgqwEBAAAAAa8BQAAAAAGwAUAAAAABxwEBAAAAAd4BAQAAAAHfASAAAAAB4AEBAAAAAeIBAAAA4gEC4wEgAAAAAeQBAQAAAAHlAUAAAAABAgAAAAEAIBwAAIUEACABxgEBAAAAAQMAAAAYACAcAACFBAAgHQAAigQAIBMAAAAYACAEAACfAwAgBQAAoAMAIAwAAKIDACANAACjAwAgDgAApAMAIA8AAKUDACAVAACKBAAgqwEBAMkCACGvAUAAygIAIbABQADKAgAhxwEBAMkCACHeAQEAyQIAId8BIACcAwAh4AEBANICACHiAQAAnQPiASLjASAAngMAIeQBAQDSAgAh5QFAAJYDACERBAAAnwMAIAUAAKADACAMAACiAwAgDQAAowMAIA4AAKQDACAPAAClAwAgqwEBAMkCACGvAUAAygIAIbABQADKAgAhxwEBAMkCACHeAQEAyQIAId8BIACcAwAh4AEBANICACHiAQAAnQPiASLjASAAngMAIeQBAQDSAgAh5QFAAJYDACERBQAA7gMAIAoAAO8DACAMAADwAwAgDQAA8QMAIA4AAPIDACAPAADzAwAgqwEBAAAAAa8BQAAAAAGwAUAAAAABxwEBAAAAAd4BAQAAAAHfASAAAAAB4AEBAAAAAeIBAAAA4gEC4wEgAAAAAeQBAQAAAAHlAUAAAAABAgAAAAEAIBwAAIsEACADAAAAGAAgHAAAiwQAIB0AAI8EACATAAAAGAAgBQAAoAMAIAoAAKEDACAMAACiAwAgDQAAowMAIA4AAKQDACAPAAClAwAgFQAAjwQAIKsBAQDJAgAhrwFAAMoCACGwAUAAygIAIccBAQDJAgAh3gEBAMkCACHfASAAnAMAIeABAQDSAgAh4gEAAJ0D4gEi4wEgAJ4DACHkAQEA0gIAIeUBQACWAwAhEQUAAKADACAKAAChAwAgDAAAogMAIA0AAKMDACAOAACkAwAgDwAApQMAIKsBAQDJAgAhrwFAAMoCACGwAUAAygIAIccBAQDJAgAh3gEBAMkCACHfASAAnAMAIeABAQDSAgAh4gEAAJ0D4gEi4wEgAJ4DACHkAQEA0gIAIeUBQACWAwAhAb0BAQAAAAEGqwEBAAAAAa8BQAAAAAGwAUAAAAABxwEBAAAAAcgBAQAAAAHJAQEAAAABAgAAAIMBACAcAACRBAAgCAMAAJADACCrAQEAAAABrwFAAAAAAbABQAAAAAHNAQEAAAAB0gEBAAAAAdMBAQAAAAHUAQIAAAABAgAAAFUAIBwAAJMEACADAAAAhgEAIBwAAJEEACAdAACXBAAgCAAAAIYBACAVAACXBAAgqwEBAMkCACGvAUAAygIAIbABQADKAgAhxwEBAMkCACHIAQEAyQIAIckBAQDSAgAhBqsBAQDJAgAhrwFAAMoCACGwAUAAygIAIccBAQDJAgAhyAEBAMkCACHJAQEA0gIAIQMAAAALACAcAACTBAAgHQAAmgQAIAoAAAALACADAACFAwAgFQAAmgQAIKsBAQDJAgAhrwFAAMoCACGwAUAAygIAIc0BAQDJAgAh0gEBANICACHTAQEA0gIAIdQBAgDRAgAhCAMAAIUDACCrAQEAyQIAIa8BQADKAgAhsAFAAMoCACHNAQEAyQIAIdIBAQDSAgAh0wEBANICACHUAQIA0QIAIREEAADtAwAgBQAA7gMAIAoAAO8DACAMAADwAwAgDQAA8QMAIA4AAPIDACCrAQEAAAABrwFAAAAAAbABQAAAAAHHAQEAAAAB3gEBAAAAAd8BIAAAAAHgAQEAAAAB4gEAAADiAQLjASAAAAAB5AEBAAAAAeUBQAAAAAECAAAAAQAgHAAAmwQAIBEEAADtAwAgBQAA7gMAIAoAAO8DACAMAADwAwAgDQAA8QMAIA8AAPMDACCrAQEAAAABrwFAAAAAAbABQAAAAAHHAQEAAAAB3gEBAAAAAd8BIAAAAAHgAQEAAAAB4gEAAADiAQLjASAAAAAB5AEBAAAAAeUBQAAAAAECAAAAAQAgHAAAnQQAIAMAAAAYACAcAACbBAAgHQAAoQQAIBMAAAAYACAEAACfAwAgBQAAoAMAIAoAAKEDACAMAACiAwAgDQAAowMAIA4AAKQDACAVAAChBAAgqwEBAMkCACGvAUAAygIAIbABQADKAgAhxwEBAMkCACHeAQEAyQIAId8BIACcAwAh4AEBANICACHiAQAAnQPiASLjASAAngMAIeQBAQDSAgAh5QFAAJYDACERBAAAnwMAIAUAAKADACAKAAChAwAgDAAAogMAIA0AAKMDACAOAACkAwAgqwEBAMkCACGvAUAAygIAIbABQADKAgAhxwEBAMkCACHeAQEAyQIAId8BIACcAwAh4AEBANICACHiAQAAnQPiASLjASAAngMAIeQBAQDSAgAh5QFAAJYDACEDAAAAGAAgHAAAnQQAIB0AAKQEACATAAAAGAAgBAAAnwMAIAUAAKADACAKAAChAwAgDAAAogMAIA0AAKMDACAPAAClAwAgFQAApAQAIKsBAQDJAgAhrwFAAMoCACGwAUAAygIAIccBAQDJAgAh3gEBAMkCACHfASAAnAMAIeABAQDSAgAh4gEAAJ0D4gEi4wEgAJ4DACHkAQEA0gIAIeUBQACWAwAhEQQAAJ8DACAFAACgAwAgCgAAoQMAIAwAAKIDACANAACjAwAgDwAApQMAIKsBAQDJAgAhrwFAAMoCACGwAUAAygIAIccBAQDJAgAh3gEBAMkCACHfASAAnAMAIeABAQDSAgAh4gEAAJ0D4gEi4wEgAJ4DACHkAQEA0gIAIeUBQACWAwAhEQQAAO0DACAFAADuAwAgCgAA7wMAIAwAAPADACAOAADyAwAgDwAA8wMAIKsBAQAAAAGvAUAAAAABsAFAAAAAAccBAQAAAAHeAQEAAAAB3wEgAAAAAeABAQAAAAHiAQAAAOIBAuMBIAAAAAHkAQEAAAAB5QFAAAAAAQIAAAABACAcAAClBAAgEQQAAO0DACAFAADuAwAgCgAA7wMAIA0AAPEDACAOAADyAwAgDwAA8wMAIKsBAQAAAAGvAUAAAAABsAFAAAAAAccBAQAAAAHeAQEAAAAB3wEgAAAAAeABAQAAAAHiAQAAAOIBAuMBIAAAAAHkAQEAAAAB5QFAAAAAAQIAAAABACAcAACnBAAgAwAAABgAIBwAAKUEACAdAACrBAAgEwAAABgAIAQAAJ8DACAFAACgAwAgCgAAoQMAIAwAAKIDACAOAACkAwAgDwAApQMAIBUAAKsEACCrAQEAyQIAIa8BQADKAgAhsAFAAMoCACHHAQEAyQIAId4BAQDJAgAh3wEgAJwDACHgAQEA0gIAIeIBAACdA-IBIuMBIACeAwAh5AEBANICACHlAUAAlgMAIREEAACfAwAgBQAAoAMAIAoAAKEDACAMAACiAwAgDgAApAMAIA8AAKUDACCrAQEAyQIAIa8BQADKAgAhsAFAAMoCACHHAQEAyQIAId4BAQDJAgAh3wEgAJwDACHgAQEA0gIAIeIBAACdA-IBIuMBIACeAwAh5AEBANICACHlAUAAlgMAIQMAAAAYACAcAACnBAAgHQAArgQAIBMAAAAYACAEAACfAwAgBQAAoAMAIAoAAKEDACANAACjAwAgDgAApAMAIA8AAKUDACAVAACuBAAgqwEBAMkCACGvAUAAygIAIbABQADKAgAhxwEBAMkCACHeAQEAyQIAId8BIACcAwAh4AEBANICACHiAQAAnQPiASLjASAAngMAIeQBAQDSAgAh5QFAAJYDACERBAAAnwMAIAUAAKADACAKAAChAwAgDQAAowMAIA4AAKQDACAPAAClAwAgqwEBAMkCACGvAUAAygIAIbABQADKAgAhxwEBAMkCACHeAQEAyQIAId8BIACcAwAh4AEBANICACHiAQAAnQPiASLjASAAngMAIeQBAQDSAgAh5QFAAJYDACEIBAYCBQoDCAALCgwEDBcJDRsJDh8KDyIKAQMAAQEDAAEDAwABBxAFCAAIAgYABAkABgIHEQUIAAcBBxIAAQcTAAIGGgELGQECBiEBCyABBgQjAAUkAAwlAA0mAA4nAA8oAAAAAAMIABAiABEjABIAAAADCAAQIgARIwASAQMAAQEDAAEDCAAXIgAYIwAZAAAAAwgAFyIAGCMAGQEDAAEBAwABBQgAHiIAISMAIkQAH0UAIAAAAAAABQgAHiIAISMAIkQAH0UAIAEDAAEBAwABAwgAJyIAKCMAKQAAAAMIACciACgjACkAAAMIAC4iAC8jADAAAAADCAAuIgAvIwAwAgYABAkABgIGAAQJAAYDCAA1IgA2IwA3AAAAAwgANSIANiMANwIGvQEBC7wBAQIGxAEBC8MBAQUIADwiAD8jAEBEAD1FAD4AAAAAAAUIADwiAD8jAEBEAD1FAD4CBtcBAQvWAQECBt4BAQvdAQEFCABFIgBIIwBJRABGRQBHAAAAAAAFCABFIgBIIwBJRABGRQBHAAAAAwgATyIAUCMAUQAAAAMIAE8iAFAjAFEQAgERKQESKwETLAEULQEWLwEXMQwYMg0ZNAEaNgwbNw4eOAEfOQEgOgwkPQ8lPhMmPwMnQAMoQQMpQgMqQwMrRQMsRwwtSBQuSgMvTAwwTRUxTgMyTwMzUAw0UxY1VBo2VgQ3VwQ4WQQ5WgQ6WwQ7XQQ8Xww9YBs-YgQ_ZAxAZRxBZgRCZwRDaAxGax1HbCNIbQJJbgJKbwJLcAJMcQJNcwJOdQxPdiRQeAJRegxSeyVTfAJUfQJVfgxWgQEmV4IBKliEAQZZhQEGWogBBluJAQZcigEGXYwBBl6OAQxfjwErYJEBBmGTAQxilAEsY5UBBmSWAQZllwEMZpoBLWebATFonAEFaZ0BBWqeAQVrnwEFbKABBW2iAQVupAEMb6UBMnCnAQVxqQEMcqoBM3OrAQV0rAEFda0BDHawATR3sQE4eLIBCnmzAQp6tAEKe7UBCny2AQp9uAEKfroBDH-7ATmAAb8BCoEBwQEMggHCATqDAcUBCoQBxgEKhQHHAQyGAcoBO4cBywFBiAHMAQmJAc0BCYoBzgEJiwHPAQmMAdABCY0B0gEJjgHUAQyPAdUBQpAB2QEJkQHbAQySAdwBQ5MB3wEJlAHgAQmVAeEBDJYB5AFElwHlAUqYAecBS5kB6AFLmgHrAUubAewBS5wB7QFLnQHvAUueAfEBDJ8B8gFMoAH0AUuhAfYBDKIB9wFNowH4AUukAfkBS6UB-gEMpgH9AU6nAf4BUg"
};
async function decodeBase64AsWasm(wasmBase64) {
  const { Buffer } = await import("buffer");
  const wasmArray = Buffer.from(wasmBase64, "base64");
  return new WebAssembly.Module(wasmArray);
}
config.compilerWasm = {
  getRuntime: async () => await import("@prisma/client/runtime/query_compiler_fast_bg.postgresql.mjs"),
  getQueryCompilerWasmModule: async () => {
    const { wasm } = await import("@prisma/client/runtime/query_compiler_fast_bg.postgresql.wasm-base64.mjs");
    return await decodeBase64AsWasm(wasm);
  },
  importName: "./query_compiler_fast_bg.js"
};
function getPrismaClientClass() {
  return runtime.getPrismaClient(config);
}

// generated/prisma/internal/prismaNamespace.ts
import * as runtime2 from "@prisma/client/runtime/client";
var getExtensionContext = runtime2.Extensions.getExtensionContext;
var NullTypes2 = {
  DbNull: runtime2.NullTypes.DbNull,
  JsonNull: runtime2.NullTypes.JsonNull,
  AnyNull: runtime2.NullTypes.AnyNull
};
var TransactionIsolationLevel = runtime2.makeStrictEnum({
  ReadUncommitted: "ReadUncommitted",
  ReadCommitted: "ReadCommitted",
  RepeatableRead: "RepeatableRead",
  Serializable: "Serializable"
});
var defineExtension = runtime2.Extensions.defineExtension;

// generated/prisma/enums.ts
var UserRole = {
  STUDENT: "STUDENT",
  TUTOR: "TUTOR",
  ADMIN: "ADMIN"
};

// generated/prisma/client.ts
globalThis["__dirname"] = path.dirname(fileURLToPath(import.meta.url));
var PrismaClient = getPrismaClientClass();

// src/lib/prisma.ts
var connectionString = process.env.DB_URL;
var adapter = new PrismaPg({ connectionString });
var prisma = new PrismaClient({ adapter });

// src/lib/auth.ts
var auth = betterAuth({
  // App and Basic Settings
  appName: "FortePath",
  basePath: "/api/v1/auth",
  trustedOrigins: [process.env.APP_URL, "http://localhost:3000"],
  // Database Settings
  database: prismaAdapter(prisma, {
    provider: "postgresql"
  }),
  // Auth Settings
  emailAndPassword: {
    enabled: true,
    autoSignIn: false,
    minPasswordLength: 6
  },
  // OAuth Providers
  socialProviders: {
    google: {
      enabled: true,
      clientId: process.env.GOOGLE_CLIENT_ID,
      clientSecret: process.env.GOOGLE_CLIENT_SECRET,
      accessType: "offline",
      prompt: "select_account consent",
      responseMode: "form_post",
      scope: ["openid", "email", "profile"]
    }
  },
  user: {
    additionalFields: {
      role: { type: "string", defaultValue: UserRole.STUDENT }
    }
  },
  session: {
    cookieCache: {
      enabled: true,
      maxAge: 15 * 60
    }
  },
  advanced: {
    cookiePrefix: "better-auth",
    useSecureCookies: process.env.NODE_ENV === "production",
    crossSubDomainCookies: {
      enabled: false
    },
    disableCSRFCheck: true
  }
});

// src/modules/tutors/tutors.router.ts
import { Router } from "express";

// src/modules/tutors/tutors.service.ts
var registerTutor = async (data) => {
  const user = await prisma.user.findUniqueOrThrow({
    where: {
      id: data.userId,
      role: UserRole.TUTOR
    }
  });
  const result = await prisma.tutorProfile.create({
    data,
    include: {
      user: {
        select: {
          name: true,
          email: true
        }
      }
    }
  });
  return result;
};
var getTutors = async (q) => {
  const conditions = [];
  const presentation = {};
  if (q.category) {
    conditions.push({
      tutorCategories: {
        some: {
          category: {
            OR: [
              {
                name: {
                  contains: q.category,
                  mode: "insensitive"
                }
              },
              {
                slug: {
                  contains: q.category,
                  mode: "insensitive"
                }
              }
            ]
          }
        }
      }
    });
  }
  if (q.search) {
    conditions.push({
      OR: [
        // Name
        {
          user: {
            name: {
              contains: q.search,
              mode: "insensitive"
            }
          }
        },
        // Designation
        {
          designation: {
            contains: q.search,
            mode: "insensitive"
          }
        },
        // Category
        {
          tutorCategories: {
            some: {
              category: {
                name: {
                  contains: q.search,
                  mode: "insensitive"
                }
              }
            }
          }
        },
        // Hourly Rate
        {
          hourlyRate: Number(q.search) || void 0
        },
        // Rating
        {
          reviews: {
            some: {
              rating: Number(q.search) || void 0
            }
          }
        }
      ]
    });
  }
  if (q.page && q.limit) {
    presentation.skip = q.limit * (q.page - 1);
    presentation.take = q.limit;
  }
  const tutors = await prisma.tutorProfile.findMany({
    where: {
      AND: conditions
    },
    skip: presentation.skip,
    take: presentation.take,
    include: {
      user: {
        select: {
          id: true,
          name: true,
          image: true,
          email: true,
          tutorReviews: {
            select: {
              rating: true,
              feedback: true
            }
          }
        }
      },
      tutorCategories: {
        select: {
          category: {
            select: { id: true, name: true, slug: true, description: true }
          }
        }
      }
    }
  });
  return { tutors, total: tutors.length };
};
var getTutor = async (id) => {
  const result = await prisma.tutorProfile.findFirstOrThrow({
    where: {
      OR: [{ id }, { userId: id }]
    },
    include: {
      user: {
        select: {
          id: true,
          name: true,
          email: true,
          image: true,
          tutorBookings: {
            include: {
              student: {
                select: {
                  id: true,
                  name: true,
                  image: true
                }
              }
            },
            omit: {
              studentId: true,
              tutorId: true
            }
          },
          tutorReviews: {
            select: {
              id: true,
              student: {
                select: {
                  id: true,
                  name: true,
                  image: true
                }
              },
              rating: true,
              feedback: true,
              createdAt: true
            }
          }
        }
      },
      tutorCategories: {
        select: {
          category: {
            select: {
              id: true,
              name: true,
              slug: true,
              description: true
            }
          }
        }
      }
    }
  });
  return result;
};
var addCategory = async (data) => {
  await prisma.category.findUniqueOrThrow({
    where: {
      id: data.categoryId
    }
  });
  await prisma.tutorProfile.findUniqueOrThrow({
    where: {
      id: data.tutorId,
      user: {
        role: UserRole.TUTOR
      }
    }
  });
  const result = await prisma.tutorCategory.create({
    data
  });
  return result;
};
var tutorsService = { registerTutor, getTutors, getTutor, addCategory };

// src/modules/tutors/tutors.controller.ts
var registerTutor2 = async (req, res) => {
  try {
    const tutor = await tutorsService.registerTutor(
      req.body
    );
    res.status(201).json({
      success: true,
      message: "Tutor profile created successfully",
      data: tutor
    });
  } catch (err) {
    res.status(500).json({
      success: false,
      message: "Unable to create tutor profile",
      error: {
        code: err.code || void 0,
        message: err.message || void 0,
        details: err
      }
    });
  }
};
var getTutors2 = async (req, res) => {
  try {
    const query = req.query;
    const category = query.category;
    const search = query.search;
    const page = Number(query.page);
    const limit = Number(query.limit);
    const queries = {
      category,
      search,
      page,
      limit
    };
    const usedQueries = Object.fromEntries(
      Object.entries(queries).filter(([_, value]) => {
        if (!value) return false;
        if (Array.isArray(value) && value.length === 0) return false;
        return true;
      })
    );
    const result = await tutorsService.getTutors(usedQueries);
    return res.status(200).json({
      success: true,
      message: "Tutors retrieved successfully",
      total: result.total,
      params: usedQueries,
      data: result.tutors
    });
  } catch (err) {
    return res.status(500).json({
      success: false,
      message: "Unable to retrieve tutors",
      error: {
        code: err.code || void 0,
        message: err.message || void 0,
        details: err
      }
    });
  }
};
var getTutor2 = async (req, res) => {
  try {
    const id = req.params.id;
    const result = await tutorsService.getTutor(id);
    return res.status(200).json({
      success: true,
      message: "Tutor retrieved successfully",
      data: result
    });
  } catch (err) {
    return res.status(500).json({
      success: false,
      message: "Unable to retrieve the tutor",
      error: {
        code: err.code || void 0,
        message: err.message || void 0,
        details: err
      }
    });
  }
};
var addCategory2 = async (req, res) => {
  try {
    const tutorCategory = await tutorsService.addCategory(req.body);
    res.status(201).json({
      success: true,
      message: "Category added to Tutor successfully",
      data: tutorCategory
    });
  } catch (err) {
    res.status(500).json({
      success: false,
      message: "Unable to add category to tutor",
      error: {
        code: err.code || void 0,
        message: err.message || void 0,
        details: err
      }
    });
  }
};
var tutorsController = { registerTutor: registerTutor2, getTutors: getTutors2, getTutor: getTutor2, addCategory: addCategory2 };

// src/middlewares/auth.ts
var auth2 = (...roles) => {
  return async (req, res, next) => {
    try {
      const session = await auth.api.getSession({
        headers: req.headers
      });
      if (!session) {
        return res.status(401).json({
          success: false,
          message: "You are unauthorized",
          error: {}
        });
      }
      req.user = {
        id: session.user.id,
        name: session.user.name,
        email: session.user.email,
        emailVerified: session.user.emailVerified,
        role: session.user.role
      };
      if (roles.length && !roles.includes(req.user.role)) {
        return res.status(403).json({
          success: false,
          message: "You lack access to this operation",
          error: {}
        });
      }
      next();
    } catch (err) {
      next(err);
    }
  };
};

// src/modules/tutors/tutors.router.ts
var router = Router();
router.post("/", tutorsController.registerTutor);
router.get("/", tutorsController.getTutors);
router.get("/:id", tutorsController.getTutor);
router.post("/categories", auth2(UserRole.TUTOR, UserRole.ADMIN), tutorsController.addCategory);

// src/modules/categories/categories.router.ts
import { Router as Router2 } from "express";

// src/modules/categories/categories.service.ts
var createCategory = async (data) => {
  const result = await prisma.category.create({
    data,
    omit: {
      updatedAt: true
    }
  });
  return result;
};
var getCategories = async (q) => {
  const conditions = [];
  const presentation = {};
  if (q.search) {
    conditions.push({
      OR: [
        // Name
        {
          name: {
            contains: q.search,
            mode: "insensitive"
          }
        },
        // Slug
        {
          slug: {
            contains: q.search,
            mode: "insensitive"
          }
        },
        // Description
        {
          description: {
            contains: q.search,
            mode: "insensitive"
          }
        }
      ]
    });
  }
  if (q.page && q.limit) {
    presentation.skip = q.limit * (q.page - 1);
    presentation.take = q.limit;
  }
  const categories = await prisma.category.findMany({
    where: {
      AND: conditions
    },
    skip: presentation.skip,
    take: presentation.take,
    include: {
      tutorCategories: {
        select: {
          tutorId: true
        }
      }
    }
  });
  return { categories, total: categories.length };
};
var getCategory = async (id) => {
  const result = await prisma.category.findUniqueOrThrow({
    where: {
      id
    },
    include: {
      tutorCategories: {
        select: {
          tutor: {
            select: {
              id: true,
              designation: true,
              bio: true,
              hourlyRate: true,
              user: {
                select: {
                  id: true,
                  name: true,
                  email: true,
                  image: true
                }
              }
            }
          }
        }
      }
    }
  });
  return result;
};
var deleteCategory = async (id) => {
  const result = await prisma.category.delete({
    where: {
      id
    },
    include: {
      tutorCategories: {
        select: {
          tutor: {
            select: {
              id: true,
              user: {
                select: {
                  name: true
                }
              }
            }
          }
        }
      }
    }
  });
  return result;
};
var categoriesService = { createCategory, getCategories, getCategory, deleteCategory };

// src/modules/categories/categories.controller.ts
var createCategory2 = async (req, res) => {
  try {
    const category = await categoriesService.createCategory(
      req.body
    );
    res.status(201).json({
      success: true,
      message: "Category created successfully",
      data: category
    });
  } catch (err) {
    res.status(500).json({
      success: false,
      message: "Unable to create category",
      error: {
        code: err.code || void 0,
        message: err.message || void 0,
        details: err
      }
    });
  }
};
var getCategories2 = async (req, res) => {
  try {
    const query = req.query;
    const search = query.search;
    const page = Number(query.page);
    const limit = Number(query.limit);
    const queries = {
      search,
      page,
      limit
    };
    const usedQueries = Object.fromEntries(
      Object.entries(queries).filter(([_, value]) => {
        if (!value) return false;
        if (Array.isArray(value) && value.length === 0) return false;
        return true;
      })
    );
    const result = await categoriesService.getCategories(usedQueries);
    return res.status(200).json({
      success: true,
      message: "Categories retrieved successfully",
      total: result.total,
      params: usedQueries,
      data: result.categories
    });
  } catch (err) {
    return res.status(500).json({
      success: false,
      message: "Unable to retrieve categories",
      error: {
        code: err.code || void 0,
        message: err.message || void 0,
        details: err
      }
    });
  }
};
var getCategory2 = async (req, res) => {
  try {
    const id = req.params.id;
    const result = await categoriesService.getCategory(id);
    return res.status(200).json({
      success: true,
      message: "Category retrieved successfully",
      data: result
    });
  } catch (err) {
    return res.status(500).json({
      success: false,
      message: "Unable to retrieve the category",
      error: {
        code: err.code || void 0,
        message: err.message || void 0,
        details: err
      }
    });
  }
};
var deleteCategory2 = async (req, res) => {
  try {
    const id = req.params.id;
    const result = await categoriesService.deleteCategory(id);
    return res.status(204).json({
      success: true,
      message: "Category removed successfully",
      data: result
    });
  } catch (err) {
    return res.status(500).json({
      success: false,
      message: "Unable to remove the category",
      error: {
        code: err.code || void 0,
        message: err.message || void 0,
        details: err
      }
    });
  }
};
var categoriesController = {
  createCategory: createCategory2,
  getCategories: getCategories2,
  getCategory: getCategory2,
  deleteCategory: deleteCategory2
};

// src/modules/categories/categories.router.ts
var router2 = Router2();
router2.post("/", auth2(UserRole.TUTOR, UserRole.ADMIN), categoriesController.createCategory);
router2.get("/", categoriesController.getCategories);
router2.get(
  "/:id",
  auth2(UserRole.STUDENT, UserRole.TUTOR, UserRole.ADMIN),
  categoriesController.getCategory
);
router2.delete("/:id", auth2(UserRole.ADMIN), categoriesController.deleteCategory);

// src/modules/reviews/reviews.router.ts
import { Router as Router3 } from "express";

// src/modules/reviews/reviews.service.ts
var createReview = async (data) => {
  const student = await prisma.user.findUniqueOrThrow({
    where: {
      id: data.studentId,
      role: {
        in: [UserRole.STUDENT, UserRole.ADMIN]
      }
    }
  });
  const tutor = await prisma.user.findUniqueOrThrow({
    where: {
      id: data.tutorId,
      role: UserRole.TUTOR
    }
  });
  const result = await prisma.review.create({
    data,
    include: {
      student: {
        select: {
          id: true,
          name: true
        }
      },
      tutor: {
        select: {
          id: true,
          name: true
        }
      }
    }
  });
  return result;
};
var getReviews = async (q) => {
  const conditions = [];
  if (q.tutorId) {
    conditions.push({
      tutorId: q.tutorId
    });
  }
  if (q.studentId) {
    conditions.push({
      studentId: q.studentId
    });
  }
  if (q.rating) {
    conditions.push({
      rating: q.rating
    });
  }
  const reviews = await prisma.review.findMany({
    where: {
      AND: conditions
    },
    include: {
      student: {
        select: {
          id: true,
          name: true,
          image: true,
          email: true
        }
      },
      tutor: {
        select: {
          id: true,
          name: true,
          image: true,
          email: true
        }
      }
    }
  });
  return { reviews, total: reviews.length };
};
var reviewsService = { createReview, getReviews };

// src/modules/reviews/reviews.controller.ts
var createReview2 = async (req, res) => {
  try {
    const review = await reviewsService.createReview(req.body);
    res.status(201).json({
      success: true,
      message: "Review created successfully",
      data: review
    });
  } catch (err) {
    res.status(500).json({
      success: false,
      message: "Unable to create review",
      error: {
        code: err.code || void 0,
        message: err.message || void 0,
        details: err
      }
    });
  }
};
var getReviews2 = async (req, res) => {
  try {
    const query = req.query;
    const tutorId = query.tutorId;
    const studentId = query.studentId;
    const rating = Number(query.rating);
    const queries = {
      tutorId,
      studentId,
      rating
    };
    const usedQueries = Object.fromEntries(
      Object.entries(queries).filter(([_, value]) => {
        if (!value) return false;
        if (Array.isArray(value) && value.length === 0) return false;
        return true;
      })
    );
    const result = await reviewsService.getReviews(usedQueries);
    return res.status(200).json({
      success: true,
      message: "Reviews retrieved successfully",
      total: result.total,
      params: usedQueries,
      data: result.reviews
    });
  } catch (err) {
    return res.status(500).json({
      success: false,
      message: "Unable to retrieve reviews",
      error: {
        code: err.code || void 0,
        message: err.message || void 0,
        details: err
      }
    });
  }
};
var reviewsController = { createReview: createReview2, getReviews: getReviews2 };

// src/modules/reviews/reviews.router.ts
var router3 = Router3();
router3.post("/", auth2(UserRole.STUDENT, UserRole.ADMIN), reviewsController.createReview);
router3.get(
  "/",
  auth2(UserRole.STUDENT, UserRole.TUTOR, UserRole.ADMIN),
  reviewsController.getReviews
);

// src/modules/bookings/bookings.router.ts
import { Router as Router4 } from "express";

// src/modules/bookings/bookings.service.ts
var createBooking = async (data) => {
  const tutor = await prisma.user.findUniqueOrThrow({
    where: {
      id: data.tutorId,
      role: UserRole.TUTOR
    }
  });
  const student = await prisma.user.findUniqueOrThrow({
    where: {
      id: data.studentId,
      role: UserRole.STUDENT
    }
  });
  const result = await prisma.booking.create({
    data,
    include: {
      student: {
        select: {
          id: true,
          name: true
        }
      },
      tutor: {
        select: {
          id: true,
          name: true
        }
      }
    }
  });
  return result;
};
var getBookings = async (q) => {
  const conditions = [];
  const presentation = {};
  if (q.tutorId) {
    conditions.push({
      tutorId: q.tutorId
    });
  }
  if (q.studentId) {
    conditions.push({
      studentId: q.studentId
    });
  }
  if (q.status) {
    conditions.push({
      status: q.status
    });
  }
  if (q.page && q.limit) {
    presentation.skip = q.limit * (q.page - 1);
    presentation.take = q.limit;
  }
  const bookings = await prisma.booking.findMany({
    where: {
      AND: conditions
    },
    skip: presentation.skip,
    take: presentation.take,
    include: {
      tutor: {
        select: {
          id: true,
          name: true,
          image: true
        }
      },
      student: {
        select: {
          id: true,
          name: true,
          image: true,
          email: true
        }
      }
    }
  });
  return { bookings, total: bookings.length };
};
var bookingsService = { createBooking, getBookings };

// src/modules/bookings/bookings.controller.ts
var createBooking2 = async (req, res) => {
  try {
    const booking = await bookingsService.createBooking(
      req.body
    );
    res.status(201).json({
      success: true,
      message: "Booking created successfully",
      data: booking
    });
  } catch (err) {
    res.status(500).json({
      success: false,
      message: "Unable to create booking",
      error: {
        code: err.code || void 0,
        message: err.message || void 0,
        details: err
      }
    });
  }
};
var getBookings2 = async (req, res) => {
  try {
    const query = req.query;
    const tutorId = query.tutorId;
    const studentId = query.studentId;
    const status = query.status;
    const page = Number(query.page);
    const limit = Number(query.limit);
    const queries = {
      tutorId,
      studentId,
      status,
      page,
      limit
    };
    const usedQueries = Object.fromEntries(
      Object.entries(queries).filter(([_, value]) => {
        if (!value) return false;
        if (Array.isArray(value) && value.length === 0) return false;
        return true;
      })
    );
    const result = await bookingsService.getBookings(usedQueries);
    return res.status(200).json({
      success: true,
      message: "Bookings retrieved successfully",
      total: result.total,
      params: usedQueries,
      data: result.bookings
    });
  } catch (err) {
    return res.status(500).json({
      success: false,
      message: "Unable to retrieve bookings",
      error: {
        code: err.code || void 0,
        message: err.message || void 0,
        details: err
      }
    });
  }
};
var bookingsController = { createBooking: createBooking2, getBookings: getBookings2 };

// src/modules/bookings/bookings.router.ts
var router4 = Router4();
router4.post("/", auth2(UserRole.STUDENT, UserRole.ADMIN), bookingsController.createBooking);
router4.get(
  "/",
  auth2(UserRole.STUDENT, UserRole.TUTOR, UserRole.ADMIN),
  bookingsController.getBookings
);

// src/modules/users/users.router.ts
import { Router as Router5 } from "express";

// src/modules/users/users.service.ts
var getUsers = async () => {
  const users = await prisma.user.findMany({
    orderBy: [
      {
        role: "asc"
      }
    ]
  });
  return { users, total: users.length };
};
var usersService = { getUsers };

// src/modules/users/users.controller.ts
var getUsers2 = async (req, res) => {
  try {
    const result = await usersService.getUsers();
    return res.status(200).json({
      success: true,
      message: "Users retrieved successfully",
      total: result.total,
      data: result.users
    });
  } catch (err) {
    return res.status(500).json({
      success: false,
      message: "Unable to retrieve users",
      error: {
        code: err.code || void 0,
        message: err.message || void 0,
        details: err
      }
    });
  }
};
var usersController = { getUsers: getUsers2 };

// src/modules/users/users.router.ts
var router5 = Router5();
router5.get("/", auth2(UserRole.ADMIN), usersController.getUsers);

// src/app.ts
var app = express();
app.use(express.json());
var allowedOrigins = [process.env.APP_URL || "http://localhost:3000"].filter(Boolean);
app.use(
  cors({
    origin: (origin, callback) => {
      if (!origin) return callback(null, true);
      const isAllowed = allowedOrigins.includes(origin) || /^https:\/\/next-blog-client.*\.vercel\.app$/.test(origin) || /^https:\/\/.*\.vercel\.app$/.test(origin);
      if (isAllowed) {
        callback(null, true);
      } else {
        callback(new Error(`Origin ${origin} not allowed by CORS`));
      }
    },
    credentials: true,
    methods: ["GET", "POST", "PUT", "DELETE", "PATCH", "OPTIONS"],
    allowedHeaders: ["Content-Type", "Authorization", "Cookie"],
    exposedHeaders: ["Set-Cookie"]
  })
);
app.all("/api/v1/auth/*splat", toNodeHandler(auth));
app.use(`${process.env.API_BASE}/users`, router5);
app.use(`${process.env.API_BASE}/tutors`, router);
app.use(`${process.env.API_BASE}/categories`, router2);
app.use(`${process.env.API_BASE}/reviews`, router3);
app.use(`${process.env.API_BASE}/bookings`, router4);
app.get("/", (_req, res) => {
  res.status(200).json({
    success: true,
    message: "Greetings to you, from FortePath"
  });
});

// src/index.ts
var index_default = app;
export {
  index_default as default
};
